import assert from 'node:assert/strict';
import test from 'node:test';
import { strToU8, zipSync } from 'fflate';
import { inspectPowerPointPresentation } from '../src/office/powerpoint/inspector.js';
const xml=(value:string)=>strToU8(value);
export function pptx(extra:Record<string,Uint8Array>={}):Uint8Array{return zipSync({
'[Content_Types].xml':xml(`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/><Override PartName="/ppt/slides/slide2.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/></Types>`),
'_rels/.rels':xml(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>`),
'ppt/presentation.xml':xml(`<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:sldIdLst><p:sldId id="256" r:id="rId1"/><p:sldId id="257" r:id="rId2"/></p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/></p:presentation>`),
'ppt/_rels/presentation.xml.rels':xml(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide2.xml"/></Relationships>`),
'ppt/slides/slide1.xml':xml(`<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:cSld><p:spTree>
<p:sp><p:nvSpPr><p:cNvPr id="2" name="Title 1"/><p:cNvSpPr/><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr b="1"/><a:t>Robot Overview</a:t></a:r></a:p></p:txBody></p:sp>
<p:sp><p:nvSpPr><p:cNvPr id="3" name="Content 2"/><p:cNvSpPr/><p:nvPr><p:ph type="body"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>Old body</a:t></a:r></a:p></p:txBody></p:sp>
<p:pic><p:nvPicPr><p:cNvPr id="4" name="Image 3"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="rIdImg"/></p:blipFill><p:spPr/></p:pic>
<p:graphicFrame><p:nvGraphicFramePr><p:cNvPr id="5" name="Table"/></p:nvGraphicFramePr><a:graphic><a:graphicData><a:tbl><a:tr><a:tc/></a:tr></a:tbl></a:graphicData></a:graphic></p:graphicFrame>
</p:spTree></p:cSld></p:sld>`),
'ppt/slides/_rels/slide1.xml.rels':xml(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdImg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image1.png"/><Relationship Id="rIdNotes" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide" Target="../notesSlides/notesSlide1.xml"/><Relationship Id="rIdChart" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart" Target="../charts/chart1.xml"/></Relationships>`),
'ppt/slides/slide2.xml':xml(`<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><p:cSld><p:spTree><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr><p:ph type="ctrTitle"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>Second</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>`),
'ppt/media/image1.png':Uint8Array.from([137,80,78,71,13,10,26,10]),
'ppt/notesSlides/notesSlide1.xml':xml('<p:notes xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"/>'),
'ppt/charts/chart1.xml':xml('<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"/>'),...extra},{level:0});}

test('PowerPoint inspector returns slide titles, shapes, images and professional totals',()=>{const result=inspectPowerPointPresentation({canonicalPath:'deck.pptx',bytes:pptx()});assert.equal(result.slides.length,2);assert.equal(result.slides[0]?.title,'Robot Overview');assert.equal(result.slides[0]?.shapes.find(x=>x.id===3)?.text,'Old body');assert.equal(result.slides[0]?.images[0]?.relationshipId,'rIdImg');assert.equal(result.slides[0]?.images[0]?.target,'ppt/media/image1.png');assert.equal(result.slides[0]?.tableCount,1);assert.equal(result.slides[0]?.chartCount,1);assert.equal(result.slides[0]?.notesPresent,true);assert.deepEqual(result.slideSizeEmu,{width:12192000,height:6858000,type:'screen16x9'});assert.deepEqual(result.totals,{slides:2,shapes:3,images:1,tables:1,charts:1,notesSlides:1});assert.equal(result.security.macrosPresent,false);});

test('PowerPoint inspector reports macro, ActiveX, embedded and external relationship surfaces',()=>{const result=inspectPowerPointPresentation({canonicalPath:'deck.pptm',bytes:pptx({'ppt/vbaProject.bin':Uint8Array.from([1]),'ppt/activeX/activeX1.bin':Uint8Array.from([2]),'ppt/embeddings/oleObject1.bin':Uint8Array.from([3]),'ppt/slides/_rels/slide2.xml.rels':xml(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdExt" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com" TargetMode="External"/></Relationships>`)})});assert.equal(result.security.macrosPresent,true);assert.equal(result.security.activeXPresent,true);assert.equal(result.security.embeddedObjectsPresent,true);assert.equal(result.security.externalRelationships.length,1);});

test('PowerPoint inspector bounds returned shapes per slide',()=>{const result=inspectPowerPointPresentation({canonicalPath:'deck.pptx',bytes:pptx(),maxShapesPerSlide:1});assert.equal(result.slides[0]?.shapes.length,1);assert.equal(result.slides[0]?.shapesTruncated,true);});
