export const midAutumnDashboardCss = String.raw`
/* Mid-Autumn flagship Overview — local preview first, production only after owner approval. */
body[data-cc-page='overview']{--ma-gold:#f5c45d;--ma-gold-soft:#d7a94a;--ma-navy:#020b1c;--ma-panel:rgba(4,17,39,.88);--ma-panel-2:rgba(5,23,52,.84)}
body[data-cc-page='overview'] .cc-page[data-page='overview']>.cc-page-head{display:none!important}
body[data-cc-page='overview'] .cc-pages{max-width:none;padding:0 14px 16px;overflow:hidden}
body[data-cc-page='overview'] .cc-page[data-page='overview'] .cc-page-grid{display:block;position:relative}
body[data-cc-page='overview'] .cc-workspace>.topbar{min-height:56px;height:56px;padding:7px 18px;background:rgba(2,10,28,.94);border-bottom:1px solid rgba(245,196,93,.18);box-shadow:0 8px 30px rgba(0,0,0,.35);backdrop-filter:blur(18px) saturate(145%)}
body[data-cc-page='overview'] .cc-topbar-breadcrumb{gap:8px}
body[data-cc-page='overview'] .cc-topbar-realm{display:none}
.ma-search-wrap{flex:1;display:flex;justify-content:center;min-width:180px}.ma-search{width:min(420px,42vw);height:34px;border:1px solid rgba(148,163,184,.22);border-radius:9px;background:rgba(4,17,39,.7);color:#dbeafe;padding:0 12px 0 34px;font-size:12px;outline:none;background-image:radial-gradient(circle at 16px 50%,transparent 5px,#91a7c7 5px,#91a7c7 6.2px,transparent 6.2px),linear-gradient(45deg,transparent 47%,#91a7c7 48%,#91a7c7 54%,transparent 55%);background-size:22px 22px,8px 8px;background-repeat:no-repeat;background-position:5px 6px,21px 20px}.ma-search:focus{border-color:rgba(245,196,93,.58);box-shadow:0 0 0 2px rgba(245,196,93,.09)}
@media(min-width:1440px){body[data-cc-page='overview'] .cc-layout{grid-template-columns:252px minmax(0,1fr)}body[data-cc-page='overview'] .cc-sidebar{width:252px;position:fixed;inset:0 auto 0 0}body[data-cc-page='overview'] .cc-workspace{grid-column:2;min-width:0}}
body[data-cc-page='overview'] .cc-sidebar{padding:16px 10px 12px;gap:14px;background:linear-gradient(180deg,rgba(2,10,28,.97) 0%,rgba(2,10,28,.90) 33%,rgba(2,10,28,.40) 66%,rgba(2,10,28,.92) 100%),var(--cc-season-rail-left) center bottom/100% auto no-repeat;border-right:1px solid rgba(245,196,93,.18);box-shadow:18px 0 55px rgba(0,0,0,.34)}
body[data-cc-page='overview'] .cc-sidebar-brand{min-height:76px;padding:5px 9px 15px;border-bottom:1px solid rgba(245,196,93,.14);background:rgba(2,10,28,.32);border-radius:12px}
body[data-cc-page='overview'] .cc-sidebar-brand img{width:48px;height:48px;border-radius:12px}
body[data-cc-page='overview'] .cc-sidebar-brand-copy b{font-size:15px;line-height:1.22;color:#fff7dc}body[data-cc-page='overview'] .cc-sidebar-brand-copy span{margin-top:3px;color:#d9bd72;font-size:10px;letter-spacing:.08em}
body[data-cc-page='overview'] .cc-nav{gap:7px}body[data-cc-page='overview'] .cc-nav button{min-height:44px;padding:10px 12px;border-radius:10px;background:rgba(3,15,36,.45);border:1px solid rgba(255,255,255,.035);font-size:13px;color:#c8d5e9}body[data-cc-page='overview'] .cc-nav button:hover{background:rgba(9,31,63,.70);border-color:rgba(245,196,93,.23);color:#fff}body[data-cc-page='overview'] .cc-nav button.active{background:linear-gradient(90deg,rgba(245,196,93,.16),rgba(13,42,76,.34));box-shadow:inset 3px 0 0 var(--ma-gold),0 0 24px rgba(245,196,93,.09);border-color:rgba(245,196,93,.25);color:#fff}
body[data-cc-page='overview'] .cc-sidebar-foot{margin-top:auto;background:rgba(2,10,28,.62);border:1px solid rgba(245,196,93,.12);border-radius:10px;padding:10px}
body[data-cc-page='overview'] .cc-seasonal-hero{height:306px;min-height:306px;margin:0 0 12px;border-radius:0 0 15px 15px;border:1px solid rgba(245,196,93,.38);box-shadow:0 24px 58px rgba(0,0,0,.5);background-size:cover;background-position:center center}
body[data-cc-page='overview'] .cc-theme-artwork .cc-seasonal-content{min-height:306px;height:306px;padding:18px 22px;grid-template-columns:1fr auto;align-items:end}
body[data-cc-page='overview'] .cc-theme-artwork .cc-seasonal-content>div:first-child{opacity:0;pointer-events:none}
body[data-cc-page='overview'] .cc-theme-artwork .cc-seasonal-side{align-self:end;justify-self:end;width:330px;max-width:330px}
body[data-cc-page='overview'] .cc-theme-artwork .cc-seasonal-event-card{padding:11px 14px;border-radius:12px;background:linear-gradient(145deg,rgba(3,11,29,.93),rgba(6,26,55,.86));border:1px solid rgba(245,196,93,.60);box-shadow:0 16px 36px rgba(0,0,0,.62),0 0 28px rgba(245,196,93,.11);backdrop-filter:blur(18px) saturate(150%)}
.ma-overview{position:relative;z-index:2;display:grid;gap:12px;padding-right:0}
.ma-cards{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}
.ma-card{min-width:0;min-height:158px;padding:14px 14px 12px;border-radius:14px;border:1px solid rgba(112,156,207,.22);background:linear-gradient(145deg,var(--ma-panel-2),var(--ma-panel));box-shadow:0 14px 34px rgba(0,0,0,.32),inset 0 1px rgba(255,255,255,.045);backdrop-filter:blur(18px) saturate(145%);overflow:hidden}
.ma-card-head{display:flex;align-items:center;gap:10px}.ma-icon{width:42px;height:42px;display:grid;place-items:center;flex:0 0 auto;border-radius:10px;font-size:20px;font-weight:900;color:#fff;box-shadow:inset 0 1px rgba(255,255,255,.22),0 8px 18px rgba(0,0,0,.26)}.ma-icon.win{background:linear-gradient(135deg,#1cb5ff,#1370d8)}.ma-icon.ubuntu{background:linear-gradient(135deg,#ff8b42,#e34a16)}.ma-icon.codex{background:linear-gradient(135deg,#f8fafc,#8fa6bf);color:#06101f}.ma-icon.agy{background:linear-gradient(135deg,#6eb5ff,#b37cff)}.ma-icon.health{background:linear-gradient(135deg,#ffe07a,#f5aa23);color:#102034}
.ma-card-title{min-width:0}.ma-card-title b{display:block;font-size:13px;color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ma-state{display:flex;align-items:center;gap:5px;margin-top:4px;color:#42e6a4;font-size:10.5px;font-weight:800}.ma-state i{width:7px;height:7px;border-radius:50%;background:#42e6a4;box-shadow:0 0 10px rgba(66,230,164,.70)}
.ma-lines{display:grid;gap:6px;margin-top:12px;padding-top:10px;border-top:1px solid rgba(255,255,255,.05)}.ma-line{font-size:10.5px;color:#a9bad0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ma-line strong{color:#dfeaff;font-weight:650}
.ma-lower{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ma-panel{min-width:0;padding:13px 15px;border-radius:14px;border:1px solid rgba(112,156,207,.18);background:linear-gradient(145deg,rgba(5,21,48,.86),rgba(3,12,29,.9));box-shadow:0 12px 30px rgba(0,0,0,.28),inset 0 1px rgba(255,255,255,.04)}
.ma-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:10px}.ma-panel-head b{display:block;color:#f3f7ff;font-size:13px}.ma-panel-head span{display:block;color:#8fa2bb;font-size:10.5px;margin-top:2px}.ma-pill{display:inline-flex!important;align-items:center;gap:5px!important;padding:3px 8px;border:1px solid rgba(66,230,164,.30);border-radius:999px;background:rgba(16,185,129,.09);color:#42e6a4!important;font-size:9.5px!important;font-weight:800}
.ma-console-row{display:flex;gap:8px}.ma-console-input{flex:1;height:34px;padding:0 10px;border:1px solid rgba(120,154,194,.24);border-radius:8px;background:rgba(1,8,22,.64);color:#dbeafe;font-size:11px}.ma-console-btn{height:34px;min-height:34px;padding:0 12px;border-radius:8px;background:rgba(245,196,93,.14);border:1px solid rgba(245,196,93,.34);color:#f8dd96;font-size:10.5px}
.ma-quick{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.ma-chip{padding:4px 8px;border-radius:7px;border:1px solid rgba(120,154,194,.18);background:rgba(1,8,22,.42);color:#9fb0c8;font-size:9.5px}
.ma-mode-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.ma-stat{padding:9px 10px;border:1px solid rgba(255,255,255,.05);border-radius:9px;background:rgba(1,8,22,.42)}.ma-stat b{display:block;color:#fff;font-size:14px}.ma-stat span{display:block;color:#90a1b8;font-size:9px;margin-top:2px}
.ma-list{display:grid;gap:0}.ma-list-row{display:grid;grid-template-columns:54px 22px minmax(0,1fr) auto;align-items:center;gap:8px;min-height:30px;border-bottom:1px solid rgba(255,255,255,.05);font-size:10px;color:#a9bad0}.ma-list-row:last-child{border-bottom:0}.ma-list-row b{color:#dfe8f5;font-size:10.5px}.ma-list-row em{font-style:normal;color:#42e6a4;font-size:9.5px;font-weight:800}.ma-list-row .warn{color:#f7b955}
@media(min-width:1440px){body[data-cc-page='overview'][data-cc-artwork='1'] .cc-page[data-page='overview']{padding-right:224px}body[data-cc-page='overview'][data-cc-artwork='1'] .cc-page[data-page='overview']:after{content:'';position:fixed;top:56px;right:0;bottom:0;width:212px;z-index:8;pointer-events:none;background:linear-gradient(180deg,rgba(2,10,28,.90) 0%,rgba(2,10,28,.18) 30%,rgba(2,10,28,.72) 100%),var(--cc-season-rail-right) center bottom/cover no-repeat;border-left:1px solid rgba(245,196,93,.14);box-shadow:-14px 0 42px rgba(0,0,0,.34)}body[data-cc-page='overview'] .cc-page[data-page='overview'] .cc-page-grid:before{inset:56px 212px 0 252px!important}.ma-card{min-height:158px}}
@media(max-width:1439px){.ma-cards{grid-template-columns:repeat(3,minmax(0,1fr))}body[data-cc-page='overview'][data-cc-artwork='1'] .cc-page[data-page='overview']{padding-right:0}.ma-search{width:min(360px,38vw)}}
@media(max-width:900px){.ma-cards{grid-template-columns:repeat(2,minmax(0,1fr))}.ma-lower{grid-template-columns:1fr}.ma-search-wrap{display:none}body[data-cc-page='overview'] .cc-seasonal-hero{height:260px;min-height:260px}body[data-cc-page='overview'] .cc-theme-artwork .cc-seasonal-content{height:260px;min-height:260px}}
@media(max-width:620px){.ma-cards{grid-template-columns:1fr}.ma-mode-grid{grid-template-columns:1fr 1fr}.ma-console-row{flex-direction:column}.ma-console-btn{width:100%}}
`;

export const midAutumnDashboardScript = String.raw`
function maSet(id,value){const el=document.getElementById(id);if(el)el.textContent=String(value??'—');}
function maEsc(v){return String(v??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]));}
function maMoveLegacyOverview(){
 const settings=document.querySelector('.cc-page[data-page="settings"] .cc-page-grid');
 if(!settings)return;
 for(const id of ['runtimeMetrics','readiness','firstRunCard']){const el=document.getElementById(id);if(el)settings.appendChild(el);}
 const runtimeMessage=document.getElementById('runtimeMessage');const runtimeCard=runtimeMessage&&runtimeMessage.closest('section.card');if(runtimeCard&&!settings.contains(runtimeCard))settings.appendChild(runtimeCard);
}
function maBuildOverview(){
 const page=document.querySelector('.cc-page[data-page="overview"]');const grid=page&&page.querySelector('.cc-page-grid');if(!page||!grid||document.getElementById('maOverview'))return;
 maMoveLegacyOverview();grid.replaceChildren();
 const root=document.createElement('div');root.id='maOverview';root.className='ma-overview';
 root.innerHTML='<section class="ma-cards">'+
  '<article class="ma-card"><div class="ma-card-head"><span class="ma-icon win">▦</span><div class="ma-card-title"><b id="maWindowsName">Windows Laptop</b><span class="ma-state"><i></i><span id="maWindowsState">ONLINE</span></span></div></div><div class="ma-lines"><div class="ma-line" id="maWindowsLine1">Local workstation</div><div class="ma-line" id="maWindowsLine2">MCP runtime</div><div class="ma-line" id="maWindowsLine3">Secure tunnel</div></div></article>'+
  '<article class="ma-card"><div class="ma-card-head"><span class="ma-icon ubuntu">●</span><div class="ma-card-title"><b id="maPersonalName">Ubuntu Personal</b><span class="ma-state"><i></i><span id="maPersonalState">PAIRED</span></span></div></div><div class="ma-lines"><div class="ma-line" id="maPersonalLine1">Trusted node</div><div class="ma-line" id="maPersonalLine2">Awaiting details</div><div class="ma-line" id="maPersonalLine3">RWMCP Direct Node</div></div></article>'+
  '<article class="ma-card"><div class="ma-card-head"><span class="ma-icon ubuntu">●</span><div class="ma-card-title"><b id="maVisionName">Ubuntu Vision</b><span class="ma-state"><i></i><span id="maVisionState">PAIRED</span></span></div></div><div class="ma-lines"><div class="ma-line" id="maVisionLine1">Trusted node</div><div class="ma-line" id="maVisionLine2">Awaiting details</div><div class="ma-line" id="maVisionLine3">RWMCP Direct Node</div></div></article>'+
  '<article class="ma-card"><div class="ma-card-head"><span class="ma-icon codex">◉</span><div class="ma-card-title"><b>Codex</b><span class="ma-state"><i></i><span id="maCodexState">—</span></span></div></div><div class="ma-lines"><div class="ma-line" id="maCodexLine1">CLI worker</div><div class="ma-line" id="maCodexLine2">Backend</div><div class="ma-line" id="maCodexLine3">Tasks today</div></div></article>'+
  '<article class="ma-card"><div class="ma-card-head"><span class="ma-icon agy">A</span><div class="ma-card-title"><b>Antigravity</b><span class="ma-state"><i></i><span id="maAgyState">—</span></span></div></div><div class="ma-lines"><div class="ma-line" id="maAgyLine1">Specialist worker</div><div class="ma-line" id="maAgyLine2">Model</div><div class="ma-line" id="maAgyLine3">Local CLI</div></div></article>'+
  '<article class="ma-card"><div class="ma-card-head"><span class="ma-icon health">⌁</span><div class="ma-card-title"><b>System Health</b><span class="ma-state"><i></i><span id="maHealthState">—</span></span></div></div><div class="ma-lines"><div class="ma-line" id="maHealthLine1">MCP</div><div class="ma-line" id="maHealthLine2">Tunnel</div><div class="ma-line" id="maHealthLine3">Authentication</div></div></article>'+
 '</section>'+
 '<section class="ma-lower"><article class="ma-panel"><div class="ma-panel-head"><div><b>Execution Console</b><span>Local runtime controls</span></div><span class="ma-pill" id="maRuntimePill">READY</span></div><div class="ma-console-row"><input class="ma-console-input" value="Runtime control" readonly><button class="ma-console-btn" id="maStartTunnel" type="button">Start tunnel</button><button class="ma-console-btn" id="maRestartRuntime" type="button">Restart</button></div><div class="ma-quick"><span class="ma-chip" id="maRuntimeVersion">MCP</span><span class="ma-chip" id="maRuntimePort">Port</span><span class="ma-chip" id="maRuntimeAuth">Auth</span></div></article>'+
 '<article class="ma-panel"><div class="ma-panel-head"><div><b>Execution Mode</b><span>Current owner policy</span></div><span class="ma-pill" id="maEffectiveMode">—</span></div><div class="ma-mode-grid"><div class="ma-stat"><b id="maConfiguredMode">—</b><span>Configured</span></div><div class="ma-stat"><b id="maModeCodex">—</b><span>Codex</span></div><div class="ma-stat"><b id="maModeAgy">—</b><span>Antigravity</span></div><div class="ma-stat"><b id="maModeOverrides">0</b><span>Overrides</span></div></div></article>'+
 '<article class="ma-panel"><div class="ma-panel-head"><div><b>Recent Activities</b><span>Live status snapshot</span></div><span class="ma-pill">LIVE</span></div><div class="ma-list" id="maActivities"></div></article>'+
 '<article class="ma-panel"><div class="ma-panel-head"><div><b>System Messages</b><span>Current local notices</span></div><span class="ma-pill" id="maNoticeCount">0</span></div><div class="ma-list" id="maMessages"></div></article></section>';
 grid.appendChild(root);
 const topbar=document.querySelector('.cc-workspace>.topbar');if(topbar&&!document.getElementById('maSearch')){const wrap=document.createElement('div');wrap.className='ma-search-wrap';wrap.innerHTML='<input id="maSearch" class="ma-search" placeholder="Search workstations, devices, commands…">';const toolbar=topbar.querySelector('.toolbar');topbar.insertBefore(wrap,toolbar||null);}
 document.getElementById('maStartTunnel').onclick=()=>runtimeAction('Start');document.getElementById('maRestartRuntime').onclick=()=>runtimeAction('Restart');
}
function maDevice(labelMatcher,fallback){const ds=pairingState&&Array.isArray(pairingState.devices)?pairingState.devices:[];return ds.find(d=>labelMatcher.test(String(d.name||d.hostname||'')))||fallback||null;}
function maRender(){
 const r=runtimeState||{},p=executionPolicyState||{},s=p.settings||{},st=p.status||{},cx=p.codex||{},agy=antigravityRuntimeState||p.antigravity||{};
 const connection=r.connectionState||((r.tunnelReady===true)?'ONLINE':(r.running?'RECONNECTING':'OFFLINE'));const mcpOk=r.mcpHealthy===true;
 maSet('maWindowsState',mcpOk?'ONLINE':r.running===true?'RUNNING':'OFFLINE');maSet('maWindowsLine1',(setupState&&setupState.platform?setupState.platform:'Windows')+' · Local');maSet('maWindowsLine2',r.mcpVersion?'MCP v'+r.mcpVersion:'MCP runtime');maSet('maWindowsLine3','Tunnel '+connection);
 const ds=pairingState&&Array.isArray(pairingState.devices)?pairingState.devices:[];const personal=maDevice(/personal/i,ds[0]);const vision=maDevice(/vision/i,ds.find(d=>d!==personal)||ds[1]);
 const fill=(d,prefix,fallback)=>{maSet(prefix+'Name',d?(d.name||d.hostname||fallback):fallback);maSet(prefix+'State',d?'PAIRED':'WAITING');maSet(prefix+'Line1',d?(d.platform||'Trusted node'):'Trusted node');maSet(prefix+'Line2',d?(d.hostname||d.id||'Direct Node'):'Awaiting pairing data');maSet(prefix+'Line3',d&&d.version?'RWMCP v'+d.version:'RWMCP Direct Node');};fill(personal,'maPersonal','Ubuntu Personal');fill(vision,'maVision','Ubuntu Vision');
 const broker=p.accountBroker||{},bs=s.codexAccountBroker||{},pool=broker.pool||{},codexReady=cx.installed===true&&((bs.enabled===true&&bs.mode==='cockpit-api-pool')?pool.healthy===true:cx.authenticated===true);maSet('maCodexState',codexReady?'READY':'OFFLINE');maSet('maCodexLine1',cx.version?'Codex CLI '+cx.version:'Codex CLI');maSet('maCodexLine2',broker.effectiveBackend||bs.mode||'native');maSet('maCodexLine3','Tasks today '+String(Number(st.codexTasksToday||0)));
 const agyReady=agy.available===true&&agy.authenticated===true;maSet('maAgyState',agyReady?'ONLINE':s.antigravityEnabled===true?'BLOCKED':'OFF');maSet('maAgyLine1','Specialist worker');maSet('maAgyLine2',agy.model&&agy.model.label?'Model '+agy.model.label:(s.antigravityModel?'Model '+s.antigravityModel:'Model auto'));maSet('maAgyLine3',agy.version?'CLI '+agy.version:'Local CLI');
 const healthy=mcpOk&&connection==='ONLINE'&&r.httpAuth==='bearer';maSet('maHealthState',healthy?'HEALTHY':'ATTENTION');maSet('maHealthLine1','MCP '+(mcpOk?'healthy':'offline'));maSet('maHealthLine2','Tunnel '+connection.toLowerCase());maSet('maHealthLine3','Auth '+String(r.httpAuth||'unknown'));
 maSet('maRuntimePill',mcpOk?'READY':r.running===true?'RUNNING':'OFFLINE');maSet('maRuntimeVersion',r.mcpVersion?'MCP v'+r.mcpVersion:'MCP');maSet('maRuntimePort',r.port?'Port '+r.port:'Port —');maSet('maRuntimeAuth','Auth '+String(r.httpAuth||'—'));
 const configured=st.configuredMode||s.defaultMode||'rwmcp-only',effective=st.effectiveMode||configured;maSet('maConfiguredMode',configured);maSet('maEffectiveMode',effective);maSet('maModeCodex',codexReady?'READY':'OFFLINE');maSet('maModeAgy',agyReady?'ONLINE':s.antigravityEnabled===true?'BLOCKED':'OFF');maSet('maModeOverrides',Number(st.activeSessionOverrides||0));
 const activities=document.getElementById('maActivities');if(activities)activities.innerHTML=[['LIVE','▦','Windows workstation',mcpOk?'Healthy':'Attention'],['LIVE','◉','Secure tunnel',connection],['LIVE','C','Codex worker',codexReady?'Ready':'Offline'],['LIVE','A','Antigravity worker',agyReady?'Online':s.antigravityEnabled===true?'Blocked':'Off']].map(x=>'<div class="ma-list-row"><span>'+x[0]+'</span><span>'+x[1]+'</span><b>'+x[2]+'</b><em>'+x[3]+'</em></div>').join('');
 const notices=[];if(updateState&&updateState.updateAvailable)notices.push(['NOW','↻','Update available','v'+String(updateState.latestVersion||'new')]);else notices.push(['NOW','✓','Software updates','Up to date']);notices.push(['NOW','●','Paired devices',String(ds.length)]);notices.push(['NOW','◇','Access mode',permissionState&&permissionState.mode?permissionState.mode:'—']);notices.push(['NOW','!','Notifications',String(currentNotificationKeys.length)]);const msgs=document.getElementById('maMessages');if(msgs)msgs.innerHTML=notices.map((x,i)=>'<div class="ma-list-row"><span>'+x[0]+'</span><span>'+x[1]+'</span><b>'+x[2]+'</b><em class="'+(i===0&&updateState&&updateState.updateAvailable?'warn':'')+'">'+x[3]+'</em></div>').join('');maSet('maNoticeCount',currentNotificationKeys.length);
}
function initMidAutumnDashboard(){if(typeof document==='undefined')return;maBuildOverview();maRender();setInterval(maRender,1000);}
`;