import path from 'node:path';
import { DOMParser, XMLSerializer, type Document, type Element, type Node } from '@xmldom/xmldom';
import { readOoxmlPackage, requirePackageEntry, type OoxmlPackage } from '../backends/ooxml/package-reader.js';
import { writeOoxmlPackage } from '../backends/ooxml/package-writer.js';
const P_NS='http://schemas.openxmlformats.org/presentationml/2006/main';const A_NS='http://schemas.openxmlformats.org/drawingml/2006/main';const R_NS='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
export type PowerPointEditOperation={type:'set_shape_text';slideIndex:number;shapeId:number;text:string}|{type:'set_slide_title';slideIndex:number;text:string};
export interface PowerPointEditResult{bytes:Uint8Array;applied:Array<{index:number;type:PowerPointEditOperation['type'];target:string}>;}
interface Relationship{id:string;target:string;targetMode?:string;}
function parseXml(bytes:Uint8Array,label:string):Document{const text=new TextDecoder().decode(bytes);if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error(`OOXML_XML_UNSAFE: DTD/entity declaration in '${label}'.`);const errors:string[]=[];const doc=new DOMParser({onError:error=>errors.push(String(error))}).parseFromString(text,'application/xml');if(!doc||errors.length)throw new Error(`OOXML_XML_INVALID: '${label}': ${errors.join('; ').slice(0,512)}`);return doc;}
function elements(root:Node,localName:string):Element[]{const out:Element[]=[];const walk=(node:Node):void=>{for(let child=node.firstChild;child;child=child.nextSibling){if(child.nodeType===1&&(child as Element).localName===localName)out.push(child as Element);walk(child);}};walk(root);return out;}
function direct(root:Node,localName:string):Element[]{const out:Element[]=[];for(let child=root.firstChild;child;child=child.nextSibling)if(child.nodeType===1&&(child as Element).localName===localName)out.push(child as Element);return out;}
function attr(e:Element,name:string,ns?:string):string|undefined{const n=ns?e.getAttributeNS(ns,name):null;if(n)return n;for(let i=0;i<e.attributes.length;i+=1){const a=e.attributes.item(i);if(a?.localName===name&&a.value)return a.value;}return undefined;}
function normalizePart(source:string,target:string):string{const normalized=target.startsWith('/')?target.replace(/^\/+/, ''):path.posix.normalize(path.posix.join(path.posix.dirname(source),target));if(normalized.startsWith('../')||normalized==='..'||path.posix.isAbsolute(normalized))throw new Error('POWERPOINT_RELATIONSHIP_UNSAFE: slide target escapes package root.');return normalized;}
function rels(pkg:OoxmlPackage):Relationship[]{const doc=parseXml(requirePackageEntry(pkg,'ppt/_rels/presentation.xml.rels'),'ppt/_rels/presentation.xml.rels');return elements(doc,'Relationship').map(e=>({id:attr(e,'Id')??'',target:attr(e,'Target')??'',targetMode:attr(e,'TargetMode')})).filter(x=>x.id&&x.target);}
function slideParts(pkg:OoxmlPackage,pres:Document):string[]{const map=new Map(rels(pkg).map(x=>[x.id,x]));return elements(pres,'sldId').map(e=>{const rid=attr(e,'id',R_NS)??attr(e,'id');const rel=rid?map.get(rid):undefined;return rel&&!rel.targetMode?normalizePart('ppt/presentation.xml',rel.target):'';}).filter(part=>part&&pkg.entries.has(part));}
function shapeId(shape:Element):number|undefined{const nv=elements(shape,'cNvPr')[0];const raw=nv?attr(nv,'id'):undefined;return raw&&/^\d+$/.test(raw)?Number(raw):undefined;}
function isTitle(shape:Element):boolean{const ph=elements(shape,'ph')[0];const type=ph?attr(ph,'type'):undefined;return type==='title'||type==='ctrTitle';}
function validateText(value:string):void{if(value.length>1_000_000||value.includes('\0'))throw new Error('PowerPoint text exceeds mutation limits or contains NUL.');if(value.split('\n').length>1000)throw new Error('PowerPoint text exceeds the 1000-paragraph limit.');}
function ensureTextBody(doc:Document,shape:Element):Element{let body=direct(shape,'txBody')[0];if(body)return body;body=doc.createElementNS(P_NS,'p:txBody');const bodyPr=doc.createElementNS(A_NS,'a:bodyPr');const listStyle=doc.createElementNS(A_NS,'a:lstStyle');body.appendChild(bodyPr);body.appendChild(listStyle);shape.appendChild(body);return body;}
function setText(doc:Document,shape:Element,value:string):void{validateText(value);const body=ensureTextBody(doc,shape);const firstRPr=elements(body,'rPr')[0]?.cloneNode(true);for(const p of direct(body,'p'))body.removeChild(p);for(const line of value.split('\n')){const p=doc.createElementNS(A_NS,'a:p');const r=doc.createElementNS(A_NS,'a:r');if(firstRPr)r.appendChild(firstRPr.cloneNode(true));const t=doc.createElementNS(A_NS,'a:t');if(/^\s|\s$|\s{2,}/.test(line))t.setAttribute('xml:space','preserve');t.appendChild(doc.createTextNode(line));r.appendChild(t);p.appendChild(r);body.appendChild(p);}}
export function editPowerPointPptx(bytes:Uint8Array,operations:PowerPointEditOperation[]):PowerPointEditResult{if(operations.length<1||operations.length>100)throw new Error('PowerPoint edit operation count must be in range 1..100.');const pkg=readOoxmlPackage(bytes);const presBytes=requirePackageEntry(pkg,'ppt/presentation.xml');const pres=parseXml(presBytes,'ppt/presentation.xml');const parts=slideParts(pkg,pres);const docs=new Map<string,Document>();const applied:PowerPointEditResult['applied']=[];const getSlide=(index:number)=>{if(!Number.isInteger(index)||index<1||index>parts.length)throw new Error(`POWERPOINT_SLIDE_NOT_FOUND: ${index}.`);const part=parts[index-1]!;let doc=docs.get(part);if(!doc){doc=parseXml(requirePackageEntry(pkg,part),part);docs.set(part,doc);}return{part,doc};};operations.forEach((op,index)=>{const{doc}=getSlide(op.slideIndex);const shapes=elements(doc,'sp');let candidates:Element[];if(op.type==='set_shape_text'){if(!Number.isInteger(op.shapeId)||op.shapeId<1)throw new Error('PowerPoint shapeId must be a positive integer.');candidates=shapes.filter(shape=>shapeId(shape)===op.shapeId);}else candidates=shapes.filter(isTitle);if(candidates.length!==1)throw new Error(`POWERPOINT_SHAPE_${candidates.length===0?'NOT_FOUND':'AMBIGUOUS'}: operation matched ${candidates.length} shapes.`);setText(doc,candidates[0]!,op.text);applied.push({index,type:op.type,target:op.type==='set_shape_text'?`slide:${op.slideIndex}/shape:${op.shapeId}`:`slide:${op.slideIndex}/title`});});const encoder=new TextEncoder();const replacements=new Map<string,Uint8Array>();for(const[part,doc]of docs)replacements.set(part,encoder.encode(new XMLSerializer().serializeToString(doc)));return{bytes:writeOoxmlPackage(pkg,replacements),applied};}
