import path from 'node:path';
import { DOMParser, type Document, type Element, type Node } from '@xmldom/xmldom';
import { createOfficeDocumentIdentity, type OfficeDocumentIdentity } from '../common/document-identity.js';
import { readOoxmlPackage, requirePackageEntry, type OoxmlPackage } from '../backends/ooxml/package-reader.js';

const R_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
export interface PowerPointShapeAst { id: number; name?: string; text: string; placeholderType?: string; isTitle: boolean; }
export interface PowerPointImageAst { id?: number; name?: string; relationshipId?: string; target?: string; external: boolean; }
export interface PowerPointSlideAst {
  index: number; part: string; relationshipId: string; title?: string; text: string; shapes: PowerPointShapeAst[]; images: PowerPointImageAst[];
  tableCount: number; chartCount: number; notesPresent: boolean; shapesTruncated: boolean;
}
export interface PowerPointInspectionResult {
  version: 1; documentId: string; identity: OfficeDocumentIdentity; slides: PowerPointSlideAst[];
  slideSizeEmu?: { width?: number; height?: number; type?: string };
  totals: { slides: number; shapes: number; images: number; tables: number; charts: number; notesSlides: number };
  security: { macrosPresent: boolean; externalRelationships: Array<{ source: string; id: string; type: string; target: string }>; embeddedObjectsPresent: boolean; activeXPresent: boolean };
  package: { entryCount: number; expandedBytes: number; presentationPart: string; warnings: string[] };
}
interface Relationship { id: string; type: string; target: string; targetMode?: string; }
function parseXml(bytes: Uint8Array, label: string): Document {
  const text = new TextDecoder('utf-8').decode(bytes); if (/<!DOCTYPE|<!ENTITY/i.test(text)) throw new Error(`OOXML_XML_UNSAFE: DTD/entity declaration is not allowed in '${label}'.`);
  const errors: string[] = []; const doc = new DOMParser({ onError: error => errors.push(String(error)) }).parseFromString(text, 'application/xml'); if (!doc || errors.length) throw new Error(`OOXML_XML_INVALID: '${label}': ${errors.join('; ').slice(0, 512)}`); return doc;
}
function elements(root: Node, localName: string): Element[] { const out: Element[] = []; const walk=(node:Node):void=>{for(let child=node.firstChild;child;child=child.nextSibling){if(child.nodeType===1&&(child as Element).localName===localName)out.push(child as Element);walk(child);}}; walk(root); return out; }
function attr(element: Element, localName: string, namespace?: string): string | undefined { const ns=namespace?element.getAttributeNS(namespace,localName):null;if(ns)return ns;for(let i=0;i<element.attributes.length;i+=1){const item=element.attributes.item(i);if(item?.localName===localName&&item.value)return item.value;}return undefined; }
function normalizePart(source: string, target: string): string { const normalized=target.startsWith('/')?target.replace(/^\/+/, ''):path.posix.normalize(path.posix.join(path.posix.dirname(source),target));if(normalized.startsWith('../')||normalized==='..'||path.posix.isAbsolute(normalized))throw new Error(`OOXML_RELATIONSHIP_UNSAFE: target '${target}' escapes package root.`);return normalized; }
function relationshipPart(sourcePart: string): string { return path.posix.join(path.posix.dirname(sourcePart),'_rels',`${path.posix.basename(sourcePart)}.rels`); }
function relationships(pkg: OoxmlPackage, sourcePart: string): Relationship[] { const bytes=pkg.entries.get(relationshipPart(sourcePart));if(!bytes)return[];const doc=parseXml(bytes,relationshipPart(sourcePart));return elements(doc,'Relationship').map(e=>({id:attr(e,'Id')??'',type:attr(e,'Type')??'',target:attr(e,'Target')??'',targetMode:attr(e,'TargetMode')})).filter(x=>x.id&&x.type&&x.target); }
function rootRelationships(pkg: OoxmlPackage): Relationship[] { const doc=parseXml(requirePackageEntry(pkg,'_rels/.rels'),'_rels/.rels');return elements(doc,'Relationship').map(e=>({id:attr(e,'Id')??'',type:attr(e,'Type')??'',target:attr(e,'Target')??'',targetMode:attr(e,'TargetMode')})).filter(x=>x.id&&x.type&&x.target); }
function presentationPart(pkg: OoxmlPackage): string { const rel=rootRelationships(pkg).find(item=>item.type.endsWith('/officeDocument'));if(!rel)throw new Error('OOXML_PACKAGE_INVALID: officeDocument relationship is missing.');const part=normalizePart('',rel.target);if(!part.startsWith('ppt/')||!pkg.entries.has(part))throw new Error('POWERPOINT_PACKAGE_INVALID: officeDocument is not a PowerPoint presentation part.');return part; }
function text(root: Node): string { return elements(root,'t').map(item=>item.textContent??'').join('\n').replace(/\n{3,}/g,'\n\n').trim(); }
function nonVisual(shape: Element): Element | undefined { return elements(shape,'cNvPr')[0]; }
function shapeAst(shape: Element): PowerPointShapeAst | undefined { const nv=nonVisual(shape);const rawId=nv?attr(nv,'id'):undefined;const id=rawId&&/^\d+$/.test(rawId)?Number(rawId):NaN;if(!Number.isInteger(id))return undefined;const placeholder=elements(shape,'ph')[0];const placeholderType=placeholder?attr(placeholder,'type'):undefined;return{id,name:nv?attr(nv,'name')?.slice(0,255):undefined,text:text(shape).slice(0,1_000_000),...(placeholderType?{placeholderType}:{}),isTitle:placeholderType==='title'||placeholderType==='ctrTitle'}; }
function imageAst(pic: Element, relMap: Map<string,Relationship>, sourcePart:string): PowerPointImageAst { const nv=nonVisual(pic);const rawId=nv?attr(nv,'id'):undefined;const id=rawId&&/^\d+$/.test(rawId)?Number(rawId):undefined;const blip=elements(pic,'blip')[0];const rid=blip?(attr(blip,'embed',R_NS)??attr(blip,'link',R_NS)??attr(blip,'embed')??attr(blip,'link')):undefined;const rel=rid?relMap.get(rid):undefined;const external=rel?.targetMode?.toLowerCase()==='external';return{...(id!==undefined?{id}:{}),...(nv&&attr(nv,'name')?{name:attr(nv,'name')!.slice(0,255)}:{}),...(rid?{relationshipId:rid}:{}),...(rel?{target:external?rel.target.slice(0,2048):normalizePart(sourcePart,rel.target)}:{}),external}; }
function inspectSlide(pkg: OoxmlPackage, part:string, index:number, relationshipId:string, maxShapes:number): PowerPointSlideAst { const doc=parseXml(requirePackageEntry(pkg,part),part);const rels=relationships(pkg,part);const relMap=new Map(rels.map(item=>[item.id,item]));const allShapes=elements(doc,'sp');const shapes=allShapes.slice(0,maxShapes).map(shapeAst).filter((item):item is PowerPointShapeAst=>Boolean(item));const images=elements(doc,'pic').slice(0,maxShapes).map(pic=>imageAst(pic,relMap,part));const title=shapes.find(item=>item.isTitle)?.text;return{index,part,relationshipId,...(title?{title}:{}),text:text(doc).slice(0,2_000_000),shapes,images,tableCount:elements(doc,'tbl').length,chartCount:rels.filter(item=>item.type.endsWith('/chart')).length,notesPresent:rels.some(item=>item.type.endsWith('/notesSlide')),shapesTruncated:allShapes.length>shapes.length}; }
export function inspectPowerPointPresentation(input:{canonicalPath:string;bytes:Uint8Array;modifiedTimeMs?:number;maxShapesPerSlide?:number}):PowerPointInspectionResult {
  const maxShapes=input.maxShapesPerSlide??500;if(!Number.isInteger(maxShapes)||maxShapes<1||maxShapes>5000)throw new Error('maxShapesPerSlide must be in range 1..5000.');const pkg=readOoxmlPackage(input.bytes);const presentation=presentationPart(pkg);const doc=parseXml(requirePackageEntry(pkg,presentation),presentation);const rels=relationships(pkg,presentation);const relMap=new Map(rels.map(item=>[item.id,item]));const slides:PowerPointSlideAst[]=[];
  for(const [zero,sldId] of elements(doc,'sldId').slice(0,5000).entries()){const rid=attr(sldId,'id',R_NS)??attr(sldId,'id');const rel=rid?relMap.get(rid):undefined;if(!rid||!rel||rel.targetMode?.toLowerCase()==='external')continue;const part=normalizePart(presentation,rel.target);if(pkg.entries.has(part))slides.push(inspectSlide(pkg,part,zero+1,rid,maxShapes));}
  const size=elements(doc,'sldSz')[0];const width=size&&/^\d+$/.test(attr(size,'cx')??'')?Number(attr(size,'cx')):undefined;const height=size&&/^\d+$/.test(attr(size,'cy')??'')?Number(attr(size,'cy')):undefined;const entries=[...pkg.entries.keys()];const externalRelationships:Array<{source:string;id:string;type:string;target:string}>=[];for(const [source,list] of [['',rootRelationships(pkg)],[presentation,rels]] as const)for(const rel of list)if(rel.targetMode?.toLowerCase()==='external')externalRelationships.push({source,id:rel.id,type:rel.type,target:rel.target.slice(0,2048)});for(const slide of slides)for(const rel of relationships(pkg,slide.part))if(rel.targetMode?.toLowerCase()==='external')externalRelationships.push({source:slide.part,id:rel.id,type:rel.type,target:rel.target.slice(0,2048)});
  const identity=createOfficeDocumentIdentity({canonicalPath:input.canonicalPath,bytes:input.bytes,modifiedTimeMs:input.modifiedTimeMs});return{version:1,documentId:identity.sha256.slice(0,16),identity,slides,...(size?{slideSizeEmu:{...(width!==undefined?{width}:{}),...(height!==undefined?{height}:{}),...(attr(size,'type')?{type:attr(size,'type')}: {})}}:{}),totals:{slides:slides.length,shapes:slides.reduce((s,x)=>s+x.shapes.length,0),images:slides.reduce((s,x)=>s+x.images.length,0),tables:slides.reduce((s,x)=>s+x.tableCount,0),charts:slides.reduce((s,x)=>s+x.chartCount,0),notesSlides:slides.filter(x=>x.notesPresent).length},security:{macrosPresent:entries.some(name=>/(^|\/)vbaProject\.bin$/i.test(name)),externalRelationships,embeddedObjectsPresent:entries.some(name=>name.startsWith('ppt/embeddings/')),activeXPresent:entries.some(name=>name.startsWith('ppt/activeX/'))},package:{entryCount:pkg.manifest.length,expandedBytes:pkg.expandedBytes,presentationPart:presentation,warnings:slides.length===0?['Presentation has no resolved slide parts.']:[]}};
}
