#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 4 ]]; then
  echo "usage: ros2-run.sh <distro-setup> <workspace-setup-or-empty> <domain-id-or-empty> <ros2-args...>" >&2
  exit 64
fi

distro_setup="$1"
workspace_setup="$2"
domain_id="$3"
shift 3

if [[ ! -f "$distro_setup" ]]; then
  echo "ROS 2 distro setup not found: $distro_setup" >&2
  exit 66
fi

# Paths are validated and generated by RWMCP before reaching this helper.
# shellcheck disable=SC1090
source "$distro_setup"

if [[ -n "$workspace_setup" ]]; then
  if [[ ! -f "$workspace_setup" ]]; then
    echo "ROS 2 workspace setup not found: $workspace_setup" >&2
    exit 66
  fi
  # shellcheck disable=SC1090
  source "$workspace_setup"
fi

if [[ -n "$domain_id" ]]; then
  export ROS_DOMAIN_ID="$domain_id"
fi

exec ros2 "$@"
