export const SERVER_VERSION = '0.32.0';
export const BUILD_CHANNEL = 'stable' as const;
export const BUILD_COMMIT = process.env.RWMCP_GIT_COMMIT?.trim() || undefined;
export const ACTION_SCHEMA_VERSION = 11;
export const ENGINEERING_API_VERSION = 5;

export type CapabilityStatus = 'available' | 'planned';

export interface CapabilityDescriptor {
  id: string;
  status: CapabilityStatus;
  tools: string[];
  note?: string;
}

export const CAPABILITIES: CapabilityDescriptor[] = [
  { id: 'chatgpt.web_control', status: 'available', tools: ['chatgpt_web_status', 'workstation_identity'], note: 'First-call end-to-end verification for ChatGPT Web plus stable per-workstation identity and a non-secret nodeHealth snapshot for direct multi-node control.' },
  { id: 'system.inspect', status: 'available', tools: ['system_info', 'capabilities_list', 'tool_discover'] },
  { id: 'software.update.check', status: 'available', tools: ['update_check'], note: 'Read-only GitHub Releases check; install/update remains owner-controlled.' },
  { id: 'setup.local_web', status: 'available', tools: [], note: 'Owner-operated loopback-only Setup & Control Center persists non-secret workstation settings outside the repository, can protect the OpenAI runtime key with Windows DPAPI, manages approval notifications, and in v0.18 manages default-deny cross-node directional grants without exposing owner policy mutation through MCP.' },
  { id: 'setup.local_tui', status: 'available', tools: [], note: 'Owner-local terminal control surface for status, access mode, MCP port, device name, tunnel binding, hidden Runtime API key rotation, and review of typed Ubuntu host-reboot approval requests. Runtime restart and host reboot remain distinct actions.' },
  { id: 'installation.windows_managed', status: 'available', tools: [], note: 'Checksum-verified Windows release installer uses versioned per-user runtime slots, a stable launcher, optional start-at-logon, and one-step rollback without requiring a Git checkout for production use.' },
  { id: 'transport.providers', status: 'available', tools: [], note: 'The CLI selects a provider behind a common contract. Current providers are local stdio and loopback Streamable HTTP.' },
  { id: 'connection.openai_secure_tunnel', status: 'available', tools: [], note: 'Optional outbound-only OpenAI Secure MCP Tunnel supervisor keeps the workstation MCP bound to loopback, injects an ephemeral bearer into tunnel runtime headers, and does not forward the OpenAI runtime API key into the MCP child process.' },
  { id: 'transport.auth.http', status: 'available', tools: [], note: 'Optional loopback HTTP bearer authentication establishes a request-scoped principal and workstation read/write/execute/full-control scopes.' },
  { id: 'multi_device.direct_nodes', status: 'available', tools: ['workstation_identity', 'chatgpt_web_status'], note: 'Preferred topology: every workstation runs its own RWMCP and OpenAI Secure MCP Tunnel, so ChatGPT can select multiple independent apps in one prompt without an SSH hub or permanent master PC.' },
  { id: 'multi_device.data_plane', status: 'available', tools: ['engineering_workflow_plan', 'engineering_workflow_run', 'chatgpt_web_status'], note: 'v0.14.3 generic workspace-file data plane remains direct-first (up to 512 MiB) with bounded relay fallback (up to 32 MiB), but cross-node movement is now default-deny and requires matching directional owner grants on both Direct Nodes plus the dedicated authenticated ChatGPT control-plane scope. Transfer contracts bind node identities, workspaces, paths, file type, size, SHA when supplied and transport; direct tickets are additionally bound to the same contract.' },
  { id: 'multi_device.authorization', status: 'available', tools: ['engineering_workflow_plan', 'engineering_workflow_run', 'chatgpt_web_status'], note: 'One Direct Node never gains implicit authority over another. Cross-node transfer requires the configured OpenAI Secure MCP Tunnel principal, exact workstation.cross_node_transfer scope, independent matching directional grants on source and destination, immediate grant re-evaluation for resumable relay sessions, and explicit allow/deny audit events. v0.18 adds owner-local Control Center grant management while keeping default-deny and exposing no MCP permission-grant surface.' },
  { id: 'multi_device.control_plane_relay', status: 'available', tools: ['engineering_workflow_plan', 'engineering_workflow_run', 'chatgpt_web_status'], note: 'Fallback transport for independent Direct Nodes that are each reachable through authenticated OpenAI Secure MCP Tunnel but cannot route directly to one another. Intended orchestration pipes bounded relay chunks between nested tool calls without rendering payload content into the chat response; direct node-to-node transport remains preferred.' },
  { id: 'control_center.offline_recovery', status: 'available', tools: [], note: 'v0.8.4 keeps the loopback Control Center usable when the runtime API key or tunnel is missing, expired, revoked, or disconnected, with local credential testing and Save & reconnect recovery.' },
  { id: 'multi_device.hub_gateway', status: 'available', tools: ['device_list', 'device_probe', 'device_exec'], note: 'Legacy/bootstrap SSH routing remains packaged for explicit recovery use but is locally DISABLED by default in v0.14.3 (legacyRemoteControl.enabled=false). Normal Direct Nodes cannot command peers.' },
  { id: 'work_session.execution', status: 'available', tools: ['work_session_create', 'work_session_resume', 'work_session_list', 'work_session_lifecycle_preview', 'work_session_checkpoint', 'work_session_close', 'work_session_worktree_prepare', 'work_session_worktree_status', 'work_session_worktree_cleanup'], note: 'v0.20 keeps resume read-only and enriches it with same-project coordination context for one-call chat handoff. lifecycle_preview mechanically reports close/cleanup eligibility without stopping resources, releasing leases, cleaning worktrees or activating the session. Explicit close/cleanup remain separate owner-directed actions.' },
  { id: 'project_session_group.coordination', status: 'available', tools: ['project_session_group_create', 'project_session_group_inspect', 'project_session_group_mutate'], note: 'Project Session Groups bind caller-owned Work Sessions to one project as coordination-only metadata. v0.18 revalidates member project identity on every view, reports aligned/drifted/degraded state, and blocks additive mutation while drift exists. Group identity never grants authorization or execution rights.' },
  { id: 'project.multichat_status', status: 'available', tools: ['project_status', 'work_session_resume', 'work_session_lifecycle_preview', 'work_session_checkpoint'], note: 'v0.20 human-managed multi-chat coordination. project_status surfaces caller-owned sessions, explicit currentTask labels, worktree state, dirty/stale sessions, shared-worktree conflicts and duplicate-task-label overlap signals. work_session_resume returns a read-only same-project handoff snapshot; currentTask may be cleared explicitly with null; lifecycle preview never mutates resources. ChatGPT Web/human judgement remains responsible for task assignment and engineering decisions.' },
  { id: 'execution.policy', status: 'available', tools: ['execution_policy_status', 'execution_policy_set_override'], note: 'v0.23 owner-managed execution policy. The loopback Control Center is authoritative for Codex enablement, default mode, budgets and fallback. ChatGPT may only set or clear a bounded Work Session override when the owner explicitly allows chat overrides. Codex quota/rate-limit detection can latch effective execution to RWMCP-only without granting new authority.' },
  { id: 'agent.worker_provider_registry', status: 'available', tools: ['worker_provider_list'], note: 'Runtime/extension-owned worker-provider registry. MCP can inspect bounded provider status and dispatch capability, but cannot register providers or grant them authority. Owner-local Control Center policy is the activation source for optional workers. Dispatch-capable coding workers require an isolated Work Session worktree and remain subordinate to ChatGPT Web planning/review authority.' },
  { id: 'agent.codex_account_broker', status: 'available', tools: ['codex_account_broker_status'], note: 'v0.25 adds an owner-selected Codex account backend. Native mode keeps the existing local ChatGPT login. Cockpit API pool mode uses only a loopback, authenticated Cockpit sidecar that is explicitly enabled, auto-routed, session-affine, cooling-aware and populated with an account pool. RWMCP reads only safe account metadata, never decrypts Cockpit credential envelopes or rewrites Codex auth.json, and injects the local gateway key only into the Codex child environment.' },
  { id: 'agent.antigravity_worker', status: 'available', tools: ['antigravity_status', 'worker_provider_list', 'work_objective_execute_task'], note: 'v0.27 integrates the official Google Antigravity CLI (agy) as an owner-enabled antigravity-local worker provider. RWMCP uses documented headless JSON/stream-json interfaces, cached system-keyring authentication, --sandbox, bounded Work Session worktrees and Git evidence. Prompts are sent through stdin stream-json rather than process argv. RWMCP never reads Google OAuth/keyring credentials and never passes --dangerously-skip-permissions.' },
  { id: 'work_session.workflow_runs', status: 'available', tools: ['engineering_workflow_run', 'work_session_resume'], note: 'Workflow runs are durably attributed to principal plus Work Session. Runtime restart reconciles incomplete records as failed instead of presenting stale running state.' },
  { id: 'work_objective.task_graph', status: 'available', tools: ['work_objective_create', 'work_objective_inspect', 'work_objective_mutate', 'work_objective_summary', 'work_objective_schedule', 'work_objective_attempts', 'work_objective_execute_task', 'work_objective_cancel_task', 'work_objective_retry_task'], note: 'Persistent Work Objectives and DAG tasks remain explicit-Work-Session scoped, deterministic and restart-reconciled. v0.19 extends persisted execution bindings from typed engineering workflows to bounded worker-provider references. Provider availability/worktree requirements are reflected by Scheduler Awareness before dispatch; execution still uses TaskExecutionCoordinator, resource leases/node interlocks and one durable Task Attempt per generation. Task/objective/provider ids are state identifiers, never authorization credentials.' },
  { id: 'quality_learning.telemetry', status: 'available', tools: ['engineering_workflow_run', 'work_session_resume'], note: 'v0.16 records bounded workflow-quality observations with deterministic evidence gates and a non-secret environment fingerprint. Collection can be disabled by the local owner; only explicit success in an explicit Work Session becomes pending-owner-review, repetition alone never promotes knowledge, and observation persistence remains advisory to workflow execution.' },
  { id: 'quality_learning.knowledge', status: 'available', tools: [], note: 'v0.16 owner-local Selective Quality Learning: approved typed-workflow evidence is aggregated into versioned reusable recommendation knowledge with quality metrics, canonical-baseline comparison, shadow evaluation and environment revalidation. Promotion/revoke/settings/history controls exist only on the loopback Control Center, never as MCP tools; promoted knowledge remains recommendation-only with executionActive=false and cannot grant scopes, change policy, auto-push Git or auto-activate execution.' },
  { id: 'workspace.discover', status: 'available', tools: ['workspace_list'] },
  { id: 'filesystem.read', status: 'available', tools: ['fs_list', 'fs_read', 'fs_find', 'fs_search_text'] },
  { id: 'filesystem.write', status: 'available', tools: ['fs_write', 'fs_patch'], note: 'Workspace policy and optimistic SHA-256 checks apply.' },
  { id: 'git.inspect', status: 'available', tools: ['git_status', 'git_diff', 'git_log', 'git_branches', 'git_worktree_list'] },
  { id: 'git.manage', status: 'available', tools: ['git_add', 'git_commit', 'git_branch_create', 'git_branch_switch', 'git_worktree_add', 'git_worktree_remove'], note: 'Typed Git writes obey workspace write policy; worktrees are the preferred concurrency boundary.' },
  { id: 'code.semantic', status: 'available', tools: ['lsp_servers', 'lsp_definition', 'lsp_references', 'lsp_hover', 'lsp_document_symbols', 'lsp_diagnostics'], note: 'Owner-configured language servers run without a shell, are executable-allowlisted, principal-scoped and message-size/time bounded. Workspace-external definition/reference paths are redacted.' },
  { id: 'process.execute', status: 'available', tools: ['process_start', 'process_write', 'process_close_stdin', 'process_read', 'process_read_since', 'process_list', 'process_stop'], note: 'v0.14.4 centralizes descendant cleanup through ProcessTreeSupervisor. Managed processes keep shell=false, bounded I/O and principal ownership; explicit stop and timeout share the same child/grandchild cleanup path with POSIX process-group TERM->grace->KILL and Windows tree-aware termination.' },
  { id: 'terminal.pty', status: 'available', tools: ['terminal_start', 'terminal_read', 'terminal_write', 'terminal_resize', 'terminal_stop'], note: 'v0.14.5 keeps the v0.14.4 per-session PTY worker isolation and adds deterministic no-shell executable resolution after policy allowlist validation, fixing Windows ConPTY startup when policy stores an executable basename such as node. Parent/worker IPC and runtime remain bounded; 200-cycle Windows soak remains the acceptance gate.' },
  { id: 'task.run', status: 'available', tools: ['task_list', 'task_run'], note: 'Owner-defined build/test profiles; resulting managed process sessions inherit principal ownership.' },
  { id: 'build.diagnostics', status: 'available', tools: ['build_diagnostics'], note: 'Token-efficient structured GCC/Clang/MSVC/CMake plus ARMCC/ArmClang/Keil/linker diagnostics parsed locally from bounded build output.' },
  { id: 'remote.ssh', status: 'available', tools: ['ssh_hosts', 'ssh_probe', 'ssh_exec'], note: 'Named owner-approved SSH hosts remain a recovery/bootstrap capability, but listing/probe/execute are gated by legacyRemoteControl.enabled and that gate defaults false. Direct-Node operation does not require workstation-to-workstation SSH.' },
  { id: 'permission.elevation', status: 'available', tools: ['permission_status'], note: 'Grant/revoke is local-owner-only and never exposed as an MCP tool. Client-bound leases use the authenticated request principal when present.' },
  { id: 'full_control.host_filesystem', status: 'available', tools: ['host_fs_list', 'host_fs_read', 'host_fs_write'], note: 'Requires full-control scope, effective Full Access and the explicit local policy gate when HTTP authentication is enabled.' },
  { id: 'full_control.shell', status: 'available', tools: ['shell_exec'], note: 'Requires full-control scope, effective Full Access and the explicit raw-shell policy gate when HTTP authentication is enabled.' },
  { id: 'full_control.admin', status: 'available', tools: ['admin_request', 'admin_request_status', 'node_reboot_request'], note: 'Privileged execution is owner-approved only. Generic admin_request remains Windows RunAs/UAC. Linux host reboot uses the typed node_reboot_request and can only be approved in the owner-local Ubuntu TUI, which rechecks Work Session interlocks and invokes the fixed systemctl reboot action via sudo without exposing a generic root shell.' },
  { id: 'engineering.workflows', status: 'available', tools: ['engineering_project_inspect', 'engineering_profile_init', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'Project-local .rwmcp/project.yaml profiles collapse repeated engineering operations into typed high-level workflows without arbitrary shell recipes. v0.22 adds ESP-IDF structured size analysis, PlatformIO JSON diagnostics, ROS 2 colcon test/rosbag inspection, bounded Docker container inspect/log workflows and validation-gated KiCad fabrication export while retaining Action Schema v6 and Engineering API v4.' },
  { id: 'engineering.hardware', status: 'available', tools: ['hardware_list', 'hardware_inspect', 'hardware_session_status'], note: 'Cross-platform serial/debug-probe discovery plus exclusive resource leases. v0.14.6 adds stable serial identity resolution by device ID, USB serial, or VID/PID with fail-closed ambiguity handling.' },
  { id: 'engineering.serial', status: 'available', tools: ['serial_open', 'serial_read', 'serial_wait_for_text', 'serial_write', 'serial_close'], note: 'Caller-owned serial sessions use bounded buffers and separately gated writes. High-level project workflows may resolve stable selectors to the current COM/tty path on every run while low-level serial_open remains explicit-path based.' },
  { id: 'engineering.firmware', status: 'available', tools: ['stm32_ioc_inspect', 'firmware_project_inspect', 'firmware_artifacts', 'firmware_provider_status', 'firmware_build', 'firmware_flash_plan', 'firmware_flash', 'firmware_verify', 'target_reset'], note: 'v0.24 adds bounded read-only STM32 CubeMX .ioc introspection for MCU/package, clock frequencies, pin/signal/labels and typed peripheral parameters without running CubeMX or project code. Existing ESP-IDF/STM32/Keil build, OpenOCD flash/verify/reset and dangerous-surface exclusions remain unchanged.' },
  { id: 'engineering.debug', status: 'available', tools: ['debug_capabilities', 'debug_session_start', 'debug_session_list', 'debug_halt', 'debug_resume', 'debug_step', 'debug_next', 'debug_stack', 'debug_registers', 'debug_variable', 'debug_breakpoint_add', 'debug_breakpoint_remove', 'debug_memory_read', 'debug_fault_snapshot', 'fault_decode', 'debug_session_stop'], note: 'Loopback-only OpenOCD + token-correlated GDB/MI with no arbitrary command, memory-write, TCL, telnet or GDB-flash surface.' },
  { id: 'engineering.ros2', status: 'available', tools: ['ros2_build', 'ros2_node_list', 'ros2_topic_list', 'ros2_topic_info', 'ros2_topic_echo', 'ros2_service_list', 'ros2_service_call', 'ros2_action_list', 'ros2_param_list', 'ros2_param_get', 'ros2_param_set', 'ros2_bag_record'], note: 'Typed colcon and ros2cli contracts separate build/runtime mutation from inspection. v0.22 adds colcon test + test-result acceptance and project-local ros2 bag info inspection; human-oriented doctor/bag reports remain bounded opaque upstream text rather than unstable parsers.' },
  { id: 'engineering.containers', status: 'available', tools: ['container_list', 'container_inspect', 'container_logs', 'container_start', 'container_stop', 'container_exec', 'image_build'], note: 'Container authority remains separate from hardware mutation and classifies host-level Docker risk before mutation. v0.22 high-level workflows add explicit container inspect and bounded log-tail evidence alongside diagnostics/stats; high-risk mutations still require full_control plus containers.allowHighRisk=true and shell/interpreter exec remains blocked.' },
  { id: 'engineering.platformio', status: 'available', tools: ['engineering_project_inspect', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'PlatformIO projects are detected from platformio.ini and retain a dedicated platformio profile kind. v0.22 diagnostics use official JSON project metadata, computed-config lint, system info and device-list outputs only; generic firmware build/upload workflows are intentionally not advertised until a dedicated typed provider models environment selection and hardware ownership.' },
  { id: 'engineering.systemd', status: 'available', tools: ['engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'Linux-only systemd diagnostics use machine-oriented systemctl show properties plus bounded JSON journal entries. Restart remains fail-closed: it always requires full_control plus an exact local-owner systemd.allowRestartUnits entry; the allowlist defaults empty.' },
  { id: 'engineering.kicad', status: 'available', tools: ['engineering_project_inspect', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'KiCad projects are detected from native project/schematic/board files. v0.22 adds validation-gated fabrication export for Gerbers, drill files and optional BOM into a caller-selected new project-local directory with per-file SHA-256 manifest. ERC/DRC remain temporary diagnostics and source-mutating upgrade/import/save-board/refill workflows are intentionally not exposed.' },
  { id: 'agent.orchestration', status: 'available', tools: ['worker_provider_list', 'work_objective_mutate', 'work_objective_schedule', 'work_objective_summary', 'work_objective_attempts', 'work_objective_execute_task', 'work_objective_cancel_task', 'work_objective_retry_task'], note: 'v0.19 Controlled Worker Orchestration delegates only persisted Work Objective tasks to locally registered providers. Dispatch enters through deterministic scheduler awareness, Work Session ownership/worktree isolation, TaskExecutionCoordinator, resource leases/node interlocks and durable Task Attempts. MCP exposes no provider registration, arbitrary shell/argv payload, permission grant, owner-policy mutation or cross-node grant path.' }
];
