export const SERVER_VERSION = '0.67.0-dev.0';
export const BUILD_CHANNEL = 'development' as const;
export const BUILD_COMMIT = process.env.RWMCP_GIT_COMMIT?.trim() || undefined;
export const ACTION_SCHEMA_VERSION = 46;
export const ENGINEERING_API_VERSION = 5;

export type CapabilityStatus = 'available' | 'planned';

export interface CapabilityDescriptor {
  id: string;
  status: CapabilityStatus;
  tools: string[];
  note?: string;
}

export const CAPABILITIES: CapabilityDescriptor[] = [
  { id: 'web.automation', status: 'available', tools: ['browser_capabilities', 'browser_provider_status', 'browser_profile_status', 'browser_session_create', 'browser_session_status', 'browser_session_close', 'browser_tabs_list', 'browser_tab_open', 'browser_tab_activate', 'browser_tab_close', 'browser_navigate', 'browser_back', 'browser_forward', 'browser_reload', 'browser_inspect', 'browser_find', 'browser_extract', 'browser_screenshot', 'browser_click', 'browser_fill', 'browser_type', 'browser_press', 'browser_select', 'browser_check', 'browser_wait', 'browser_upload', 'browser_download', 'browser_download_status', 'browser_existing_chrome_status', 'browser_existing_session_open', 'browser_existing_session_status', 'browser_existing_session_close', 'browser_existing_inspect', 'browser_existing_find', 'browser_existing_extract', 'browser_existing_click', 'browser_existing_fill'], note: 'Phase B-F browser platform. Managed Chrome/Edge provides background-first semantic automation, bounded file I/O and dedicated persistent profiles. Existing Chrome Bridge uses an owner-installed Manifest V3 extension plus authenticated local Native Messaging so already-authenticated NotebookLM tabs can be claimed by one principal + Work Session without automating Google login. Password inputs, cookies, tokens, raw JavaScript/selectors/CDP, coordinate clicks and LAN debugging endpoints are not exposed.' },
  { id: 'web.notebooklm', status: 'available', tools: ['notebooklm_session_open', 'notebooklm_session_status', 'notebooklm_session_close', 'notebooklm_sources_list', 'notebooklm_video_status', 'notebooklm_video_generate', 'notebooklm_content_pipeline', 'notebooklm_video_pipeline_v3', 'notebooklm_ask'], note: 'NotebookLM site adapter over Existing Chrome. v0.55 adds Video Pipeline v3: exact per-video source sets through semantic checkbox state, production profiles, durable owner-scoped queue resume, persisted artifact metadata and bounded quality gates for selected-source count and duplicate accepted artifacts. v0.52 content pipeline and v0.51 single/batch commands remain backward compatible. All paths require an owner-authenticated NotebookLM tab and use bounded semantic operations; Google login, credentials/tokens/cookies, raw selectors, JavaScript and coordinate control remain out of scope.' },
  { id: 'chatgpt.web_control', status: 'available', tools: ['chatgpt_web_status', 'workstation_identity'], note: 'First-call end-to-end verification for ChatGPT Web plus stable per-workstation identity and a non-secret nodeHealth snapshot for direct multi-node control.' },
  { id: 'system.inspect', status: 'available', tools: ['system_info', 'capabilities_list', 'tool_discover'] },
  { id: 'office.core', status: 'available', tools: ['office_capabilities'], note: 'Office Pack core provides deterministic capability discovery plus typed document identity, session, transaction, validation and backend-selection boundaries. Office remains a sibling capability pack, not a reasoning worker.' },
  { id: 'office.word.inspect', status: 'available', tools: ['word_inspect'], note: 'Phase B read-only Word OOXML inspection returns a bounded structural AST for headings, paragraphs, tables, media, OMML equations and sections. ZIP/package limits and active-content reporting are fail-closed; macros and external relationships are never executed/followed.' },
  { id: 'office.word.mutate', status: 'available', tools: ['word_edit'], note: 'Phase E Word mutation uses typed bounded operations, explicit Work Session ownership, per-file write leases, SHA-256 optimistic concurrency, backup/working-copy transactions, rollback records, OMML equations and optional native Word open/PDF/OMath acceptance.' },
  { id: 'office.excel.inspect', status: 'available', tools: ['excel_inspect'], note: 'v0.44 adds bounded Excel OOXML inspection for sheets, typed cells, formulas, defined names, tables and active/external content reporting without starting Excel or following links.' },
  { id: 'office.excel.mutate', status: 'available', tools: ['excel_edit'], note: 'v0.44 Excel mutation is .xlsx-only and transactional: typed cell/range/formula edits, explicit Work Session ownership, per-file lease, SHA-256 conflict detection, owner-scoped rollback and optional native Excel recalculation/formula-error/PDF acceptance. Vendor hardening statically blocks external/side-effect formulas before native Excel and scopes AutomationSecurity to the Open call.' },
  { id: 'office.powerpoint.inspect', status: 'available', tools: ['powerpoint_inspect'], note: 'v0.44 adds bounded PowerPoint OOXML inspection for slides, titles, shapes, images, tables, charts, notes and active/external content reporting without starting PowerPoint or following relationships.' },
  { id: 'office.powerpoint.mutate', status: 'available', tools: ['powerpoint_edit'], note: 'v0.44 PowerPoint mutation is .pptx-only and text-only: existing title/shape edits use explicit Work Session ownership, per-file lease, SHA-256 conflict detection, structural count invariants, owner-scoped rollback and optional native PowerPoint read-only open/PDF acceptance. Vendor hardening preserves simple paragraph/run formatting in-place and fails closed on mixed formatting, hyperlinks or paragraph reshaping instead of flattening styles.' },
  { id: 'software.update.check', status: 'available', tools: ['update_check'], note: 'Read-only GitHub Releases check; install/update remains owner-controlled.' },
  { id: 'setup.local_web', status: 'available', tools: [], note: 'Owner-operated loopback-only Setup & Control Center persists non-secret workstation settings outside the repository, can protect the OpenAI runtime key with Windows DPAPI, manages approval notifications, and in v0.18 manages default-deny cross-node directional grants without exposing owner policy mutation through MCP.' },
  { id: 'setup.local_tui', status: 'available', tools: [], note: 'Owner-local terminal control surface for status, access mode, MCP port, device name, tunnel binding, hidden Runtime API key rotation, and review of typed Ubuntu host-reboot approval requests. Runtime restart and host reboot remain distinct actions.' },
  { id: 'installation.windows_managed', status: 'available', tools: [], note: 'Checksum-verified Windows release installer uses versioned per-user runtime slots, a stable launcher, optional start-at-logon, and one-step rollback without requiring a Git checkout for production use.' },
  { id: 'transport.providers', status: 'available', tools: [], note: 'The CLI selects a provider behind a common contract. Current providers are local stdio and loopback Streamable HTTP.' },
  { id: 'connection.openai_secure_tunnel', status: 'available', tools: [], note: 'Optional outbound-only OpenAI Secure MCP Tunnel supervisor keeps the workstation MCP bound to loopback, injects an ephemeral bearer into tunnel runtime headers, and does not forward the OpenAI runtime API key into the MCP child process.' },
  { id: 'transport.auth.http', status: 'available', tools: [], note: 'Optional loopback HTTP bearer authentication establishes a request-scoped principal and workstation read/write/execute/full-control scopes.' },
  { id: 'multi_device.direct_nodes', status: 'available', tools: ['workstation_identity', 'chatgpt_web_status'], note: 'Preferred topology: every workstation runs its own RWMCP and OpenAI Secure MCP Tunnel, so ChatGPT can select multiple independent apps in one prompt without an SSH hub or permanent master PC.' },
  { id: 'multi_device.data_plane', status: 'available', tools: ['engineering_workflow_plan', 'engineering_workflow_run', 'chatgpt_web_status'], note: 'v0.14.3 generic workspace-file data plane remains direct-first (up to 512 MiB) with bounded relay fallback (up to 32 MiB), but cross-node movement is now default-deny and requires matching directional owner grants on both Direct Nodes plus the dedicated authenticated ChatGPT control-plane scope. Transfer contracts bind node identities, workspaces, paths, file type, size, SHA when supplied and transport; direct tickets are additionally bound to the same contract.' },
  { id: 'multi_device.authorization', status: 'available', tools: ['engineering_workflow_plan', 'engineering_workflow_run', 'chatgpt_web_status'], note: 'One Direct Node never gains implicit authority over another. Cross-node transfer requires the configured OpenAI Secure MCP Tunnel principal, exact workstation.cross_node_transfer scope, independent matching directional grants on source and destination, immediate grant re-evaluation for resumable relay sessions, and explicit allow/deny audit events. v0.18 adds owner-local Control Center grant management while keeping default-deny and exposing no MCP permission-grant surface.' },
  { id: 'multi_device.control_plane_relay', status: 'available', tools: ['engineering_workflow_plan', 'engineering_workflow_run', 'chatgpt_web_status'], note: 'Fallback transport for independent Direct Nodes that are each reachable through authenticated OpenAI Secure MCP Tunnel but cannot route directly to one another. Intended orchestration pipes bounded relay chunks between nested tool calls without rendering payload content into the chat response; direct node-to-node transport remains preferred.' },
  { id: 'control_center.offline_recovery', status: 'available', tools: [], note: 'v0.8.4 keeps the loopback Control Center usable when the runtime API key or tunnel is missing, expired, revoked, or disconnected, with local credential testing and Save & reconnect recovery.' },
  { id: 'multi_device.hub_gateway', status: 'available', tools: ['device_list', 'device_probe', 'device_exec'], note: 'Legacy/bootstrap SSH routing remains packaged for explicit recovery use but is locally DISABLED by default in v0.14.3 (legacyRemoteControl.enabled=false). Normal Direct Nodes cannot command peers.' },
  { id: 'work_session.execution', status: 'available', tools: ['work_session_create', 'work_session_resume', 'work_session_list', 'work_session_lifecycle_preview', 'work_session_checkpoint', 'work_session_close', 'work_session_worktree_prepare', 'work_session_worktree_status', 'work_session_worktree_cleanup'], note: 'v0.20 keeps resume read-only and enriches it with same-project coordination context for one-call chat handoff. lifecycle_preview mechanically reports close/cleanup eligibility without stopping resources, releasing leases, cleaning worktrees or activating the session. Explicit close/cleanup remain separate owner-directed actions.' },
  { id: 'project_session_group.coordination', status: 'available', tools: ['project_session_group_create', 'project_session_group_inspect', 'project_session_group_mutate'], note: 'Project Session Groups bind caller-owned Work Sessions to one project as coordination-only metadata. v0.18 revalidates member project identity on every view, reports aligned/drifted/degraded state, and blocks additive mutation while drift exists. Group identity never grants authorization or execution rights.' },
  { id: 'project.multichat_status', status: 'available', tools: ['project_status', 'work_session_resume', 'work_session_lifecycle_preview', 'work_session_checkpoint'], note: 'v0.20 human-managed multi-chat coordination. project_status surfaces caller-owned sessions, explicit currentTask labels, worktree state, dirty/stale sessions, shared-worktree conflicts and duplicate-task-label overlap signals. work_session_resume returns a read-only same-project handoff snapshot; currentTask may be cleared explicitly with null; lifecycle preview never mutates resources. ChatGPT Web/human judgement remains responsible for task assignment and engineering decisions.' },
  { id: 'execution.policy', status: 'available', tools: ['execution_policy_status', 'execution_policy_set_override', 'execution_target_set_override'], note: 'v0.42 makes the owner-managed execution policy generic across rwmcp-direct, codex-local and antigravity-local. The canonical targetPolicy carries enabled targets, generic fallback and per-target budgets while v0.41 Codex-centric fields remain as a compatibility projection for rollback and older clients. Work Session overrides may only narrow the owner route and never widen provider or workstation authority.' },
  { id: 'agent.worker_provider_registry', status: 'available', tools: ['worker_provider_list'], note: 'Runtime/extension-owned worker-provider registry. MCP can inspect bounded provider status and dispatch capability, but cannot register providers or grant them authority. Owner-local Control Center policy is the activation source for optional workers. Dispatch-capable coding workers require an isolated Work Session worktree and remain subordinate to ChatGPT Web planning/review authority.' },
  { id: 'agent.routing', status: 'available', tools: ['worker_route_plan'], note: 'v0.42 plans RWMCP direct, Codex and Antigravity as peer execution targets from the generic target policy plus Work Session narrowing and task affinity. Codex and Antigravity both honor independent local task budgets; readiness, fallback latches and worktree ownership remain authoritative. Route planning is read-only advisory and never grants authority or transfers dirty ownership.' },
  { id: 'agent.codex_account_broker', status: 'available', tools: ['codex_account_broker_status'], note: 'v0.25 adds an owner-selected Codex account backend. Native mode keeps the existing local ChatGPT login. Cockpit API pool mode uses only a loopback, authenticated Cockpit sidecar that is explicitly enabled, auto-routed, session-affine, cooling-aware and populated with an account pool. RWMCP reads only safe account metadata, never decrypts Cockpit credential envelopes or rewrites Codex auth.json, and injects the local gateway key only into the Codex child environment.' },
  { id: 'agent.antigravity_worker', status: 'available', tools: ['antigravity_status', 'worker_provider_list', 'work_objective_execute_task'], note: 'v0.27 integrates the official Google Antigravity CLI (agy) as an owner-enabled antigravity-local worker provider. RWMCP uses documented headless JSON/stream-json interfaces, cached system-keyring authentication, --sandbox, bounded Work Session worktrees and Git evidence. Prompts are sent through stdin stream-json rather than process argv. RWMCP never reads Google OAuth/keyring credentials and never passes --dangerously-skip-permissions.' },
  { id: 'work_session.workflow_runs', status: 'available', tools: ['engineering_workflow_run', 'work_session_resume'], note: 'Workflow runs are durably attributed to principal plus Work Session. Runtime restart reconciles incomplete records as failed instead of presenting stale running state.' },
  { id: 'work_objective.task_graph', status: 'available', tools: ['work_objective_create', 'work_objective_inspect', 'work_objective_decompose', 'work_objective_mutate', 'work_objective_summary', 'work_objective_schedule', 'work_objective_attempts', 'work_objective_execution_timeline', 'work_objective_execute_wave', 'work_objective_execute_task', 'work_objective_cancel_task', 'work_objective_retry_task'], note: 'Persistent Work Objectives and DAG tasks remain explicit-Work-Session scoped, deterministic and restart-reconciled. v0.43 adds atomic ChatGPT-supplied decomposition with local task keys and bounded wave execution while preserving scheduler/lease/interlock authority. v0.41 adds a mechanically derived stage-only execution timeline plus provider cancellation that preserves cancelled as a distinct terminal state. Codex and Antigravity dispatches can receive a task-generation-scoped AbortSignal and terminate their supervised process tree; final persisted task/attempt state remains authoritative. Task/objective/provider ids are state identifiers, never authorization credentials.' },
  { id: 'quality_learning.telemetry', status: 'available', tools: ['engineering_workflow_run', 'work_session_resume'], note: 'v0.16 records bounded workflow-quality observations with deterministic evidence gates and a non-secret environment fingerprint. Collection can be disabled by the local owner; only explicit success in an explicit Work Session becomes pending-owner-review, repetition alone never promotes knowledge, and observation persistence remains advisory to workflow execution.' },
  { id: 'quality_learning.knowledge', status: 'available', tools: [], note: 'v0.16 owner-local Selective Quality Learning: approved typed-workflow evidence is aggregated into versioned reusable recommendation knowledge with quality metrics, canonical-baseline comparison, shadow evaluation and environment revalidation. Promotion/revoke/settings/history controls exist only on the loopback Control Center, never as MCP tools; promoted knowledge remains recommendation-only with executionActive=false and cannot grant scopes, change policy, auto-push Git or auto-activate execution.' },
  { id: 'workspace.discover', status: 'available', tools: ['workspace_list'] },
  { id: 'filesystem.read', status: 'available', tools: ['fs_list', 'fs_read', 'fs_find', 'fs_search_text'] },
  { id: 'filesystem.write', status: 'available', tools: ['fs_write', 'fs_patch'], note: 'Workspace policy and optimistic SHA-256 checks apply.' },
  { id: 'git.inspect', status: 'available', tools: ['git_status', 'git_diff', 'git_log', 'git_branches', 'git_worktree_list'] },
  { id: 'git.manage', status: 'available', tools: ['git_add', 'git_commit', 'git_branch_create', 'git_branch_switch', 'git_worktree_add', 'git_worktree_remove'], note: 'Typed Git writes obey workspace write policy; worktrees are the preferred concurrency boundary.' },
  { id: 'code.semantic', status: 'available', tools: ['lsp_servers', 'lsp_definition', 'lsp_references', 'lsp_hover', 'lsp_document_symbols', 'lsp_diagnostics'], note: 'Owner-configured language servers run without a shell, are executable-allowlisted, principal-scoped and message-size/time bounded. Workspace-external definition/reference paths are redacted.' },
  { id: 'process.execute', status: 'available', tools: ['process_start', 'process_write', 'process_close_stdin', 'process_read', 'process_read_since', 'process_list', 'process_stop'], note: 'v0.14.4 centralizes descendant cleanup through ProcessTreeSupervisor. Managed processes keep shell=false, bounded I/O and principal ownership; explicit stop and timeout share the same child/grandchild cleanup path with POSIX process-group TERM->grace->KILL and Windows tree-aware termination.' },
  { id: 'terminal.pty', status: 'available', tools: ['terminal_start', 'terminal_read', 'terminal_write', 'terminal_resize', 'terminal_stop'], note: 'v0.14.5 keeps the v0.14.4 per-session PTY worker isolation and adds deterministic no-shell executable resolution after policy allowlist validation, fixing Windows ConPTY startup when policy stores an executable basename such as node. Parent/worker IPC and runtime remain bounded; 200-cycle Windows soak remains the acceptance gate.' },
  { id: 'task.run', status: 'available', tools: ['task_list', 'task_run'], note: 'Owner-defined build/test profiles; resulting managed process sessions inherit principal ownership.' },
  { id: 'build.diagnostics', status: 'available', tools: ['build_diagnostics'], note: 'Token-efficient structured GCC/Clang/MSVC/CMake plus ARMCC/ArmClang/Keil/linker diagnostics parsed locally from bounded build output.' },
  { id: 'remote.ssh', status: 'available', tools: ['ssh_hosts', 'ssh_probe', 'ssh_exec'], note: 'Named owner-approved SSH hosts remain a recovery/bootstrap capability, but listing/probe/execute are gated by legacyRemoteControl.enabled and that gate defaults false. Direct-Node operation does not require workstation-to-workstation SSH.' },
  { id: 'permission.elevation', status: 'available', tools: ['permission_status'], note: 'Grant/revoke is local-owner-only and never exposed as an MCP tool. Client-bound leases use the authenticated request principal when present.' },
  { id: 'full_control.host_filesystem', status: 'available', tools: ['host_fs_list', 'host_fs_read', 'host_fs_write'], note: 'Requires full-control scope, effective Full Access and the explicit local policy gate when HTTP authentication is enabled.' },
  { id: 'full_control.shell', status: 'available', tools: ['shell_exec'], note: 'Requires full-control scope, effective Full Access and the explicit raw-shell policy gate when HTTP authentication is enabled.' },
  { id: 'full_control.admin', status: 'available', tools: ['admin_request', 'admin_request_status', 'node_reboot_request'], note: 'Privileged execution is owner-approved only. Windows generic admin_request remains RunAs/UAC. Linux owner-local approval stays typed and bounded: Control Center may approve the exact host reboot or validated apt-get install -y package requests through the desktop authorization agent, while the TUI retains the typed reboot path through sudo. Work Session interlocks and exact command hashes are rechecked before privileged execution, and no generic root shell is exposed.' },
  { id: 'engineering.workflows', status: 'available', tools: ['engineering_project_inspect', 'engineering_profile_init', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'Project-local .rwmcp/project.yaml profiles collapse repeated engineering operations into typed high-level workflows without arbitrary shell recipes. v0.50 adds CMSIS-SVD-driven STM32 live peripheral intelligence. stm32.peripheral_snapshot and optional stm32.deep_diagnostics snapshots resolve project-scoped semantic peripheral/register names into bounded GDB/MI reads only after fail-closed SVD safety checks for inheritance, access, width, arrays, field completeness/layout and readAction side effects. Callers cannot provide raw addresses or write registers. Workflow growth continues through the generic workflow envelope instead of adding top-level authority.' },
  { id: 'engineering.hardware', status: 'available', tools: ['hardware_list', 'hardware_inspect', 'hardware_session_status'], note: 'Cross-platform serial/debug-probe discovery plus exclusive resource leases. v0.14.6 adds stable serial identity resolution by device ID, USB serial, or VID/PID with fail-closed ambiguity handling.' },
  { id: 'engineering.serial', status: 'available', tools: ['serial_open', 'serial_read', 'serial_wait_for_text', 'serial_write', 'serial_close'], note: 'Caller-owned serial sessions use bounded buffers and separately gated writes. High-level project workflows may resolve stable selectors to the current COM/tty path on every run while low-level serial_open remains explicit-path based.' },
  { id: 'engineering.can', status: 'available', tools: ['can_provider_status', 'can_interface_list', 'can_interface_status', 'can_capture'], note: 'v0.54 adds Linux SocketCAN read-only diagnostics and bounded capture. Interface state and CAN bit-timing/error counters come from machine-readable iproute2/netlink output; traffic capture prefers linux-can candump and falls back to a packaged fixed Python AF_CAN receiver when candump is unavailable; both paths require an explicit interface, at most 32 typed id/mask filters, at most 1000 frames and bounded inactivity timeout. Interface mutation, bitrate changes, frame transmission, replay, bus-off restart and CAN gateway mutation remain unavailable.' },
  { id: 'engineering.camera', status: 'available', tools: ['camera_provider_status', 'camera_profile_list', 'camera_profile_inspect', 'camera_rtsp_probe', 'camera_stream_metadata', 'camera_ptz_status', 'camera_ptz_move', 'camera_ptz_stop'], note: 'Camera Diagnostics Phase 2 retains bounded RTSP/ffprobe observation and adds owner-local ONVIF WS-Security PTZ status plus normalized bounded ContinuousMove/Stop. PTZ credentials are resolved only from owner-controlled environment variables and are redacted from MCP output; move duration is capped at 2000 ms and auto-stopped. Raw SOAP/XML, arbitrary PTZ endpoints, two-way audio, camera configuration and snapshot/output mutation remain unavailable.' },
  { id: 'engineering.canopen', status: 'available', tools: ['canopen_provider_status', 'canopen_capture_decode', 'canopen_node_observe'], note: 'CANopen Phase 1 adds passive CiA 301 diagnostics on Linux SocketCAN. Bounded captures classify standard 11-bit NMT, SYNC, EMCY, PDO, SDO and Heartbeat traffic; node observation summarizes heartbeat/NMT state, boot-up, EMCY and SDO/PDO evidence. Empty node lists discover only nodes already visible in captured traffic. Frame transmission, NMT commands, active SDO requests/writes, PDO transmission, LSS, node-guarding requests and bus configuration remain unavailable.' },
  { id: 'engineering.mqtt', status: 'available', tools: ['mqtt_provider_status', 'mqtt_subscribe_sample', 'mqtt_agv_lift_observe'], note: 'MQTT diagnostics Phase 1 adds bounded MQTT 3.1.1 subscribe-only observation through owner-local profiles. Credentials are never accepted as MCP arguments; optional passwords are resolved only from owner-selected runtime environment variables. Generic topic samples decode bounded UTF-8/JSON payloads, and the AGV helper observes aubotagv vehicle state topics to extract liftSensorStatus evidence. PUBLISH, retained mutation, broker configuration and credential mutation remain unavailable.' },
  { id: 'engineering.media', status: 'available', tools: ['media_provider_status', 'media_file_probe', 'media_transcode_plan', 'media_transcode', 'media_remotion_status', 'media_comfyui_status', 'media_comfyui_preset_list', 'media_comfyui_job_plan', 'media_comfyui_job_submit', 'media_comfyui_job_status', 'media_comfyui_artifact_plan', 'media_comfyui_artifact_import'], note: 'Media/Video Phase 1 adds typed project-scoped FFprobe inspection, fixed-preset FFmpeg MP4 transcoding with fail-if-exists and partial-output cleanup, Remotion package inspection, and read-only ComfyUI system/queue health. Raw FFmpeg arguments, arbitrary process execution, arbitrary ComfyUI workflow submission/model download; Phase 2 allows only owner-local preset submission with typed whitelisted bindings, implicit overwrite and arbitrary output formats remain unavailable.' },
  { id: 'engineering.modbus_tcp', status: 'available', tools: ['modbus_tcp_provider_status', 'modbus_tcp_endpoint_status', 'modbus_tcp_read', 'modbus_tcp_probe'], note: 'Modbus TCP Phase 1 adds cross-platform read-only diagnostics over one explicit host/port. Functions 01/02/03/04 validate MBAP transaction/protocol/length/unit fields, bounded address/quantity/timeouts and protocol exception responses. Probe accepts only 1..32 explicit unique Unit IDs and never scans a subnet or implicit 0..255 range. Write functions, raw PDU injection and server configuration remain unavailable.' },
  { id: 'engineering.opcua', status: 'available', tools: ['opcua_provider_status', 'opcua_endpoint_describe', 'opcua_browse', 'opcua_read'], note: 'OPC UA Phase 1 adds cross-platform anonymous read-only opc.tcp diagnostics using the node-opcua client stack. Endpoint metadata, bounded forward Browse and bounded Read are supported through an in-memory certificate/key provider so no PKI files are written. Phase 1 fixes SecurityPolicy/MessageSecurityMode to None and intentionally excludes username/password identity, certificate enrollment, Write, Method Call, subscriptions, monitored-item mutation, history update and node management.' },
  { id: 'engineering.industrial_profiles', status: 'available', tools: ['industrial_profile_list', 'industrial_profile_inspect', 'industrial_profile_preflight'], note: 'Industrial Endpoint Profiles Phase 1 provides owner-local, non-secret semantic endpoint descriptors for Modbus RTU, Modbus TCP, OPC UA and MQTT/AGV. Profiles are inspectable through MCP but mutation remains owner-local/out-of-band. Preflight is bounded and read-only: explicit serial endpoint discovery for Modbus RTU, TCP reachability for Modbus TCP, GetEndpoints for OPC UA, and connect/subscribe without payload disclosure for MQTT/AGV.' },
  { id: 'engineering.modbus_rtu', status: 'available', tools: ['modbus_rtu_provider_status', 'modbus_rtu_endpoint_status', 'modbus_rtu_read', 'modbus_rtu_probe'], note: 'v0.62 adds cross-platform typed Modbus RTU diagnostics over explicit serial endpoints. Phase 1 supports only read functions 01/02/03/04 with CRC16 validation, protocol exception decoding, bounded address/quantity/timeouts and up to 32 explicit unique Unit IDs for probing. Each transaction holds the shared serial resource lease so it cannot race serial monitor/flash activity. Write functions, broadcast writes, raw RTU frame injection and implicit full-bus scans remain unavailable.' },
  { id: 'engineering.network', status: 'available', tools: ['network_provider_status', 'network_interface_list', 'network_route_list', 'network_dns_lookup', 'network_ping', 'network_tcp_reachability'], note: 'v0.63 adds cross-platform read-only typed network diagnostics: bounded interface inventory, route inventory, DNS lookup, ICMP ping and TCP connect reachability. Hostnames/IPs, ports, counts and timeouts are validated; ping/route commands are fixed by the adapter and no raw arguments are exposed. IP/DNS/route/firewall configuration, packet injection and packet capture remain unavailable.' },
  { id: 'engineering.firmware', status: 'available', tools: ['stm32_ioc_inspect', 'stm32_svd_inspect', 'firmware_project_inspect', 'firmware_artifacts', 'firmware_memory_report', 'firmware_provider_status', 'firmware_build', 'firmware_flash_plan', 'firmware_flash', 'firmware_verify', 'target_reset'], note: 'v0.24 adds bounded read-only STM32 CubeMX .ioc introspection for MCU/package, clock frequencies, pin/signal/labels and typed peripheral parameters without running CubeMX or project code. v0.44 adds bounded ELF/AXF memory analysis with Flash/RAM totals, section sizes and top symbols. Vendor hardening aligns OpenOCD flash/deploy with the upstream single program+verify+reset+exit helper while preserving standalone verify and dangerous-surface exclusions. v0.45 adds bounded project-scoped CMSIS-SVD device/peripheral/register/field inspection without target connection or register writes.' },
  { id: 'engineering.esp32', status: 'available', tools: ['esp32_preflight', 'firmware_project_inspect', 'firmware_artifacts', 'firmware_build', 'firmware_flash_plan', 'firmware_flash', 'serial_open', 'serial_read', 'serial_wait_for_text', 'serial_close', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'v0.65 extends the v0.64 ESP32/ESP-IDF hardening with typed Python-environment and compiler provenance, bounded IDF_SKIP_CHECK_SUBMODULES policy, profile-aware espidf.preflight, and build-lease-scoped espidf.fullclean/reconfigure workflows. Runtime Python/SDK mismatch blocks build and flash; stale compiler provenance from an existing build blocks flash while still allowing a rebuild to repair metadata. Build directories are checked for symlink escape before maintenance/build/flash. eFuse writes, Secure Boot key burning, flash-encryption key mutation, erase-flash, arbitrary environment maps, arbitrary esptool arguments and raw ROM commands remain intentionally unavailable.' },
  { id: 'engineering.debug', status: 'available', tools: ['debug_capabilities', 'debug_session_start', 'debug_session_list', 'debug_halt', 'debug_resume', 'debug_step', 'debug_next', 'debug_stack', 'debug_registers', 'debug_locals', 'debug_rtos_tasks', 'debug_variable', 'debug_disassemble', 'debug_breakpoint_add', 'debug_breakpoint_remove', 'debug_watchpoint_add', 'debug_watchpoint_remove', 'debug_memory_read', 'debug_fault_snapshot', 'debug_cortexm_exception_frame', 'fault_decode', 'debug_session_stop'], note: 'Loopback-only OpenOCD + token-correlated GDB/MI. v0.44 adds bounded locals, disassembly and safe-expression watchpoints while retaining no arbitrary command, memory-write, TCL, telnet or GDB-flash surface. Vendor hardening avoids claiming hardware guarantee for default write watchpoints because GDB may fall back to software; read/access watchpoints remain hardware-required upstream. v0.45 replaces regex-oriented GDB/MI result parsing with a bounded recursive MI grammar while keeping the same typed debugger authority boundary. v0.47 adds read-only Cortex-M architectural exception-frame decoding and target-provided RTOS/thread inventory through documented GDB/MI `-thread-info`; optional RTOS awareness is bounded to none/auto/FreeRTOS and no arbitrary Tcl, TCB offset parsing or memory/register write surface is introduced.' },
  { id: 'engineering.ros2', status: 'available', tools: ['ros2_build', 'ros2_node_list', 'ros2_node_info', 'ros2_topic_list', 'ros2_topic_info', 'ros2_topic_echo', 'ros2_topic_hz', 'ros2_topic_bw', 'ros2_tf_lookup', 'ros2_service_list', 'ros2_service_call', 'ros2_action_list', 'ros2_action_info', 'ros2_lifecycle_get', 'ros2_lifecycle_list', 'ros2_lifecycle_set', 'ros2_param_list', 'ros2_param_get', 'ros2_param_set', 'ros2_bag_record'], note: 'Typed colcon and ros2cli contracts separate build/runtime mutation from inspection. v0.45 adds an optional rclpy-native JSON diagnostic path for topic rate/bandwidth and TF when an explicit ROS distro is configured; unavailable rclpy falls back to the existing bounded CLI path. v0.44 adds node introspection, bounded topic rate/bandwidth sampling, TF2 lookup, lifecycle inspection/allowlisted transitions and action endpoint inspection. Vendor hardening labels Hz/BW as subscriber-observed measurements affected by QoS and host load rather than publisher/link ground truth. Action goal dispatch is intentionally deferred until RWMCP can guarantee goal-handle cancellation on timeout. v0.22 colcon test, bag inspection and bounded opaque doctor reports remain available.' },
  { id: 'engineering.containers', status: 'available', tools: ['container_list', 'container_inspect', 'container_logs', 'container_start', 'container_stop', 'container_exec', 'image_build'], note: 'Container authority remains separate from hardware mutation and classifies host-level Docker risk before mutation. v0.22 high-level workflows add explicit container inspect and bounded log-tail evidence alongside diagnostics/stats; high-risk mutations still require full_control plus containers.allowHighRisk=true and shell/interpreter exec remains blocked.' },
  { id: 'engineering.platformio', status: 'available', tools: ['engineering_project_inspect', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'PlatformIO projects are detected from platformio.ini and retain a dedicated platformio profile kind. v0.53 adds typed platformio.build and platformio.upload workflows: one validated environment is selected explicitly or from the project profile, upload requires one exact port/address or stable serial selector, hardware mutation policy remains authoritative, and upload holds a resource lease for the complete official pio run --target upload command. Arbitrary uploader commands, raw flags, wildcard ports and shell recipes are not exposed.' },
  { id: 'engineering.systemd', status: 'available', tools: ['engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'Linux-only systemd diagnostics use machine-oriented systemctl show properties plus bounded JSON journal entries. Restart remains fail-closed: it always requires full_control plus an exact local-owner systemd.allowRestartUnits entry; the allowlist defaults empty.' },
  { id: 'engineering.kicad', status: 'available', tools: ['kicad_ipc_prepare', 'kicad_ipc_status', 'kicad_ipc_board_inspect', 'kicad_ipc_footprint_move', 'kicad_ipc_footprint_update', 'kicad_ipc_batch_place', 'kicad_ipc_routing_inspect', 'kicad_ipc_track_add', 'kicad_ipc_track_update', 'kicad_ipc_via_add', 'kicad_ipc_via_update', 'kicad_provider_status', 'kicad_board_stats', 'kicad_drc', 'kicad_erc', 'kicad_validate', 'kicad_bom_report', 'kicad_edit_inspect', 'kicad_edit', 'engineering_project_inspect', 'engineering_workflow_list', 'engineering_workflow_plan', 'engineering_workflow_run'], note: 'v0.61 adds KiCad IPC Phase 6 typed routing primitives. `kicad_ipc_routing_inspect` exposes bounded live nets, tracks, vias and zones. Straight-track add/update and through-via add/update require Work Session ownership, exact live-board SHA, explicit net/layer identity, per-board lease, DRC non-regression and compensating rollback/removal, with no implicit save. Arc-track mutation, routing-item deletion, blind/buried/micro vias, zone mutation/refill and autorouting remain unavailable until rollback semantics are strong enough. v0.60 footprint live editing and v0.59 IPC setup/path hardening remain active. `kicad_ipc_footprint_update` changes only Value, lock, exclude-from-BOM, exclude-from-position, DNP and not-in-schematic fields; `kicad_ipc_batch_place` moves/rotates 1..32 unique unlocked footprints in one official KiCad commit. Both require Work Session ownership and an exact live-board fingerprint, hold the board lease, compare before/after DRC, compensate rollback on regression and never save implicitly. v0.59 setup/path hardening remains active. `kicad_ipc_prepare` provides bounded Windows setup: it detects the installed KiCad major version, refuses while KiCad/PCB Editor is running, backs up the matching common config, and only enables `api.enable_server`. Live board identity now resolves official KiCad project-path metadata (with a strict authorized-path fallback for basename-only API responses), fixing the v0.58 false mismatch discovered by real KiCad 10.0.6 acceptance. v0.58 live control remains available. RWMCP discovers an isolated owner-local kicad-python provider, verifies the active PCB resolves to the explicitly authorized project board, exposes read-only live board/footprint inspection with a SHA-256 board fingerprint, and provides typed live footprint movement through official kipy commits. Live moves require Work Session ownership plus the exact board fingerprint, create an undo step, compare before/after DRC snapshots, automatically restore the prior pose on regression, and intentionally do not save the board to disk. Raw scripts/selectors, raw kicad_dru mutation, arbitrary BOM plugins/scripts, routing-item deletion, arc-track mutation, blind/buried/micro vias, zone mutation/refill, autorouting and implicit board save remain unavailable.' },
  { id: 'agent.orchestration', status: 'available', tools: ['worker_provider_list', 'work_objective_decompose', 'work_objective_mutate', 'work_objective_schedule', 'work_objective_summary', 'work_objective_attempts', 'work_objective_execution_timeline', 'work_objective_execute_wave', 'work_objective_execute_task', 'work_objective_cancel_task', 'work_objective_retry_task'], note: 'v0.43 adds atomic ChatGPT-supplied objective decomposition plus one bounded scheduler-ready wave per execution call. auto-worker assignment is deterministic from task affinity and the v0.42 generic target policy; RWMCP does not run a second planner model. AI worker tasks are serialized inside a shared Work Session worktree, compatible deterministic tasks may execute in parallel, and Scheduler Awareness, resource leases/node interlocks, safe cancellation and durable Task Attempts remain authoritative.' }
];

export function capabilitiesForPlatform(platform: NodeJS.Platform | string = process.platform): CapabilityDescriptor[] {
  return platform === 'win32' ? CAPABILITIES : CAPABILITIES.filter(capability => !capability.id.startsWith('office.'));
}
